//! Breeze Framework - sequenced tasks as comptime-generated state machines.
//!
//! # Why not protothreads
//!
//! The C prototype of this framework used Contiki-style protothreads: a
//! `case __LINE__:` label inside a `switch` gave straight-line code a
//! resumable call/return. That trick cannot be expressed in Zig at all - Zig
//! `switch` prongs never fall through, and there is no `goto`, so there is no
//! way to jump into the middle of a block.
//!
//! Zig 0.16 also removed `async`/`await` as language features; the new
//! `std.Io` is an *interface* for host I/O backends (thread pool, io_uring,
//! kqueue) and offers no freestanding implementation for Cortex-M or RISC-V.
//!
//! So instead of resuming a stack, a task here is a *program*: a comptime list
//! of instructions. The state machine, the dispatch, and the jump targets are
//! all generated by the compiler. What protothreads bought with a stack trick,
//! this buys with comptime - and it is strictly better on three counts:
//!
//!   * no `__LINE__` magic, so two waits on one line cannot collide and a file
//!     longer than 65535 lines cannot break;
//!   * no `-Wimplicit-fallthrough` noise, which the C version had to suppress
//!     at every single wait point;
//!   * the whole saved state is one index, and `@sizeOf` is known at comptime.
//!
//! # Cost
//!
//! A program costs one `u32` program counter plus a `Tick` wait origin plus two
//! flags. It does not grow with the number of instructions, and no stack is
//! saved - unlike a stackful coroutine, which needs its own stack per task.

const std = @import("std");
const tick = @import("tick.zig");
const Tick = tick.Tick;

/// One instruction of a sequenced task.
///
/// Instructions are tagged so the generated dispatch is a plain jump table;
/// there is no interpreter loop over an opaque bytecode.
pub fn Instr(comptime Ctx: type) type {
    return union(enum) {
        /// Run an action, then advance unconditionally.
        call: *const fn (*Ctx) void,
        /// Run an action until it returns true, then advance.
        ///
        /// This is the "poll a driver" primitive: the action runs on every
        /// scheduler pass and decides for itself when it is done.
        call_until: *const fn (*Ctx) bool,
        /// Wait a fixed number of milliseconds from first reaching this
        /// instruction.
        wait_ms: u32,
        /// Wait until any bit in `mask` is present in the event snapshot.
        wait_event: u32,
        /// Wait until a predicate becomes true.
        wait_for: *const fn (*Ctx) bool,
        /// Jump to the given instruction index if a predicate is true.
        ///
        /// This is what makes the instruction list a real state machine rather
        /// than a straight line: with it, retry and give-up logic is expressed
        /// directly instead of being smuggled into a `wait_for` predicate.
        branch_if: BranchIf(Ctx),
        /// Wait until either an event arrives or a timeout expires.
        ///
        /// Records which one happened in `Program.timed_out` so that the
        /// following `branch_timeout` / `branch_event` can react. This is the
        /// shape almost every protocol handshake needs.
        wait_event_timeout: WaitEventTimeout,
        /// Jump to the given instruction index if the last timed wait expired.
        branch_timeout: u32,
        /// Jump to the given instruction index if the last timed wait was
        /// satisfied by an event.
        branch_event: u32,
        /// Unconditional jump. Jumping to index 0 restarts the program, which
        /// is how a cyclic task is written.
        jump: u32,
        /// End the program early. The program counter resets, so the next poll
        /// restarts from instruction 0.
        finish,
    };
}

pub const WaitEventTimeout = struct {
    mask: u32,
    timeout_ms: u32,
};

/// Predicate plus jump target, for `Instr.branch_if`.
pub fn BranchIf(comptime Ctx: type) type {
    return struct {
        pred: *const fn (*Ctx) bool,
        target: u32,
    };
}

/// Outcome of one poll of a `Program`.
pub const Step = enum {
    /// The program suspended; poll again on the next scheduler pass.
    pending,
    /// The program ran to completion (or hit `finish`) during this pass.
    finished,
};

/// Compile a program: a comptime instruction list becomes a task body.
///
/// ```zig
/// const Ctx = struct { tx: u8 = 0, acked: bool = false };
///
/// fn send(ctx: *Ctx) void { ctx.tx += 1; }
///
/// const program = breeze.Program(Ctx, &.{
///     .{ .call = send },
///     .{ .wait_event_timeout = .{ .mask = ACK, .timeout_ms = 50 } },
///     .{ .branch_timeout = 3 },   // retry
///     .{ .finish },
/// });
/// ```
pub fn Program(comptime Ctx: type, comptime instrs: []const Instr(Ctx)) type {
    if (instrs.len == 0) {
        @compileError("Program requires at least one instruction");
    }
    validateJumps(Ctx, instrs);

    return struct {
        const Self = @This();

        /// Number of instructions, known at comptime.
        pub const len = instrs.len;

        /// Upper bound on instructions executed per poll. A program built only
        /// from `jump` instructions would otherwise spin the scheduler; the
        /// budget converts that bug into a bounded, observable stall.
        pub const max_instrs_per_poll: u32 = @intCast(instrs.len + 1);

        /// Instruction index. This is the entire resumable state.
        pc: u32 = 0,

        /// Timebase origin for the wait currently in progress.
        wait_start: Tick = 0,

        /// Whether a timed wait is in progress (its origin is valid).
        waiting: bool = false,

        /// Whether the most recent `wait_event_timeout` expired.
        ///
        /// Deliberately *not* part of the resume state and not cleared by
        /// `reset`: it is an outcome record, so a task can still report "the
        /// last exchange timed out" after the program has looped back to the
        /// start. It is overwritten by the next `wait_event_timeout`.
        timed_out: bool = false,

        /// True when the program is at its start and not mid-wait.
        pub fn isAtStart(self: *const Self) bool {
            return self.pc == 0 and !self.waiting;
        }

        /// Return to instruction 0, abandoning any wait in progress.
        ///
        /// `timed_out` survives, because it describes what already happened
        /// rather than where execution resumes.
        pub fn reset(self: *Self) void {
            self.pc = 0;
            self.waiting = false;
        }

        /// Advance the program.
        ///
        /// `events` is a snapshot of the event masks, taken once per scheduler
        /// pass so that every task sees a consistent view.
        pub fn poll(self: *Self, ctx: *Ctx, now: Tick, events: u32) Step {
            var budget: u32 = max_instrs_per_poll;

            while (true) {
                if (self.pc >= instrs.len) {
                    self.reset();
                    return .finished;
                }
                if (budget == 0) {
                    return .pending;
                }
                budget -= 1;

                switch (instrs[self.pc]) {
                    .call => |f| {
                        f(ctx);
                        self.pc += 1;
                    },
                    .call_until => |f| {
                        if (f(ctx)) self.pc += 1 else return .pending;
                    },
                    .wait_ms => |ms| {
                        if (!self.waiting) {
                            self.wait_start = now;
                            self.waiting = true;
                        }
                        if (tick.elapsed(self.wait_start, now) >= ms) {
                            self.waiting = false;
                            self.pc += 1;
                        } else return .pending;
                    },
                    .wait_event => |mask| {
                        if ((events & mask) != 0) self.pc += 1 else return .pending;
                    },
                    .wait_for => |f| {
                        if (f(ctx)) self.pc += 1 else return .pending;
                    },
                    .branch_if => |b| {
                        self.pc = if (b.pred(ctx)) b.target else self.pc + 1;
                    },
                    .wait_event_timeout => |w| {
                        if ((events & w.mask) != 0) {
                            self.timed_out = false;
                            self.waiting = false;
                            self.pc += 1;
                        } else {
                            if (!self.waiting) {
                                self.wait_start = now;
                                self.waiting = true;
                            }
                            if (tick.elapsed(self.wait_start, now) >= w.timeout_ms) {
                                self.timed_out = true;
                                self.waiting = false;
                                self.pc += 1;
                            } else return .pending;
                        }
                    },
                    .branch_timeout => |target| {
                        self.pc = if (self.timed_out) target else self.pc + 1;
                    },
                    .branch_event => |target| {
                        self.pc = if (self.timed_out) self.pc + 1 else target;
                    },
                    .jump => |target| {
                        self.pc = target;
                    },
                    .finish => {
                        self.pc = instrs.len;
                    },
                }
            }
        }
    };
}

/// Reject out-of-range jump targets at compile time rather than trapping at
/// runtime on a device with no debugger attached.
fn validateJumps(comptime Ctx: type, comptime instrs: []const Instr(Ctx)) void {
    inline for (instrs, 0..) |instr, i| {
        switch (instr) {
            .jump => |t| checkTarget(t, instrs.len, i),
            .branch_timeout => |t| checkTarget(t, instrs.len, i),
            .branch_event => |t| checkTarget(t, instrs.len, i),
            .branch_if => |b| checkTarget(b.target, instrs.len, i),
            else => {},
        }
    }
}

fn checkTarget(comptime target: u32, comptime len: usize, comptime from: usize) void {
    if (target >= len) {
        @compileError(std.fmt.comptimePrint(
            "jump target {d} at instruction {d} is out of range (program has {d} instructions)",
            .{ target, from, len },
        ));
    }
}

// --- tests -----------------------------------------------------------------
//
// Zig has no nested function declarations, so the actions referenced by test
// programs live in this namespace. Program instructions hold plain function
// pointers, which is why `{ .call = T.inc }` works without any closure.

const T = struct {
    const Ctx = struct {
        n: u32 = 0,
        hits: u32 = 0,
        ok: u32 = 0,
        bad: u32 = 0,
        tries: u32 = 0,
        laps: u32 = 0,
    };

    fn inc(c: *Ctx) void {
        c.n += 1;
    }
    fn hit(c: *Ctx) void {
        c.hits += 1;
    }
    fn markOk(c: *Ctx) void {
        c.ok += 1;
    }
    fn markBad(c: *Ctx) void {
        c.bad += 1;
    }
    fn lap(c: *Ctx) void {
        c.laps += 1;
    }
    fn ready(c: *Ctx) bool {
        c.tries += 1;
        return c.tries >= 3;
    }
};

test "linear program runs to completion" {
    const P = Program(T.Ctx, &.{
        .{ .call = T.inc },
        .{ .call = T.inc },
        .{ .call = T.inc },
    });

    var ctx = T.Ctx{};
    var p = P{};

    try std.testing.expectEqual(Step.finished, p.poll(&ctx, 0, 0));
    try std.testing.expectEqual(@as(u32, 3), ctx.n);
    try std.testing.expect(p.isAtStart());
}

test "wait_ms suspends then resumes at the deadline" {
    const P = Program(T.Ctx, &.{
        .{ .call = T.inc },
        .{ .wait_ms = 100 },
        .{ .call = T.inc },
    });

    var ctx = T.Ctx{};
    var p = P{};

    // t=0: runs inc, then arms the 100 ms wait.
    try std.testing.expectEqual(Step.pending, p.poll(&ctx, 0, 0));
    try std.testing.expectEqual(@as(u32, 1), ctx.n);

    // t=50: still waiting, and the action must not re-run.
    try std.testing.expectEqual(Step.pending, p.poll(&ctx, 50, 0));
    try std.testing.expectEqual(@as(u32, 1), ctx.n);

    // t=101: wait satisfied, second inc runs.
    try std.testing.expectEqual(Step.finished, p.poll(&ctx, 101, 0));
    try std.testing.expectEqual(@as(u32, 2), ctx.n);
}

test "wait_ms origin is the first arrival, not the first poll after it" {
    const P = Program(T.Ctx, &.{ .{ .wait_ms = 100 }, .{ .call = T.inc } });

    var ctx = T.Ctx{};
    var p = P{};

    _ = p.poll(&ctx, 1000, 0); // arms at t=1000
    try std.testing.expectEqual(Step.pending, p.poll(&ctx, 1050, 0));
    try std.testing.expectEqual(@as(u32, 0), ctx.n);
    try std.testing.expectEqual(Step.finished, p.poll(&ctx, 1101, 0));
    try std.testing.expectEqual(@as(u32, 1), ctx.n);
}

test "wait_event blocks until the mask appears" {
    const ACK: u32 = 0b0100;
    const P = Program(T.Ctx, &.{
        .{ .wait_event = ACK },
        .{ .call = T.hit },
    });

    var ctx = T.Ctx{};
    var p = P{};

    try std.testing.expectEqual(Step.pending, p.poll(&ctx, 0, 0));
    try std.testing.expectEqual(Step.pending, p.poll(&ctx, 10, 0b0010));
    try std.testing.expectEqual(@as(u32, 0), ctx.hits);
    try std.testing.expectEqual(Step.finished, p.poll(&ctx, 20, ACK));
    try std.testing.expectEqual(@as(u32, 1), ctx.hits);
}

test "wait_event_timeout takes the event branch" {
    const ACK: u32 = 0b0001;
    // Layout note: each arm ends in `.finish`. Without it the success arm would
    // fall through into the failure arm - exactly the class of bug that makes
    // hand-written state machines drift over time.
    //
    // `.finish` carries no payload, so the array type has to be spelled out for
    // the bare tag literal to be inferable.
    const instrs = [_]Instr(T.Ctx){
        // 0
        .{ .wait_event_timeout = .{ .mask = ACK, .timeout_ms = 50 } },
        // 1: timed out -> failure arm at 4; otherwise fall through to success
        .{ .branch_timeout = 4 },
        // 2
        .{ .call = T.markOk },
        // 3
        .finish,
        // 4
        .{ .call = T.markBad },
        // 5
        .finish,
    };
    const P = Program(T.Ctx, &instrs);

    var ctx = T.Ctx{};
    var p = P{};

    try std.testing.expectEqual(Step.pending, p.poll(&ctx, 0, 0));
    try std.testing.expectEqual(Step.finished, p.poll(&ctx, 20, ACK));
    try std.testing.expectEqual(@as(u32, 1), ctx.ok);
    try std.testing.expectEqual(@as(u32, 0), ctx.bad);
    try std.testing.expect(!p.timed_out);
}

test "wait_event_timeout takes the timeout branch" {
    const ACK: u32 = 0b0001;
    const instrs = [_]Instr(T.Ctx){
        .{ .wait_event_timeout = .{ .mask = ACK, .timeout_ms = 50 } },
        .{ .branch_timeout = 4 },
        .{ .call = T.markOk },
        .finish,
        .{ .call = T.markBad },
        .finish,
    };
    const P = Program(T.Ctx, &instrs);

    var ctx = T.Ctx{};
    var p = P{};

    _ = p.poll(&ctx, 0, 0);
    try std.testing.expectEqual(Step.pending, p.poll(&ctx, 30, 0));
    try std.testing.expectEqual(Step.finished, p.poll(&ctx, 51, 0));
    try std.testing.expectEqual(@as(u32, 0), ctx.ok);
    try std.testing.expectEqual(@as(u32, 1), ctx.bad);
    try std.testing.expect(p.timed_out);
}

test "call_until polls a driver until it reports done" {
    const P = Program(T.Ctx, &.{.{ .call_until = T.ready }});

    var ctx = T.Ctx{};
    var p = P{};

    try std.testing.expectEqual(Step.pending, p.poll(&ctx, 0, 0));
    try std.testing.expectEqual(Step.pending, p.poll(&ctx, 1, 0));
    try std.testing.expectEqual(Step.finished, p.poll(&ctx, 2, 0));
    try std.testing.expectEqual(@as(u32, 3), ctx.tries);
}

test "cyclic program repeats, and its state does not grow with instruction count" {
    const P = Program(T.Ctx, &.{
        .{ .call = T.lap },
        .{ .wait_ms = 10 },
        .{ .jump = 0 },
    });

    var ctx = T.Ctx{};
    var p = P{};

    _ = p.poll(&ctx, 0, 0); // lap 1, arm wait
    try std.testing.expectEqual(Step.pending, p.poll(&ctx, 11, 0)); // lap 2
    try std.testing.expectEqual(@as(u32, 2), ctx.laps);

    // pc (4) + wait_start (4) + two flags (2, padded) = 12 bytes, independent
    // of how many instructions the program has.
    try std.testing.expectEqual(@as(usize, 12), @sizeOf(@TypeOf(p)));
}

test "a jump-only program cannot spin the scheduler forever" {
    const P = Program(T.Ctx, &.{
        .{ .jump = 1 },
        .{ .jump = 0 },
    });

    var ctx = T.Ctx{};
    var p = P{};

    // Returns rather than hanging: the per-poll budget converts the bug into a
    // bounded stall, which a watchdog can then act on.
    try std.testing.expectEqual(Step.pending, p.poll(&ctx, 0, 0));
    try std.testing.expectEqual(Step.pending, p.poll(&ctx, 0, 0));
}

test "reset abandons a wait in progress" {
    const P = Program(T.Ctx, &.{
        .{ .wait_ms = 1000 },
        .{ .call = T.inc },
    });

    var ctx = T.Ctx{};
    var p = P{};

    try std.testing.expectEqual(Step.pending, p.poll(&ctx, 0, 0));
    try std.testing.expect(!p.isAtStart());
    p.reset();
    try std.testing.expect(p.isAtStart());
    try std.testing.expectEqual(@as(u32, 0), p.pc);
}

test "wait_ms of zero does not suspend" {
    const P = Program(T.Ctx, &.{
        .{ .wait_ms = 0 },
        .{ .call = T.inc },
    });

    var ctx = T.Ctx{};
    var p = P{};

    try std.testing.expectEqual(Step.finished, p.poll(&ctx, 1234, 0));
    try std.testing.expectEqual(@as(u32, 1), ctx.n);
}
