//! Breeze scheduler demo - runs on the host with a virtual clock.
//!
//! This is the shape of a real firmware superloop, with the clock replaced by a
//! simulator so it can run (and be asserted on) on a workstation. On target,
//! only the `hal` import changes; see `examples/firmware_cortex_m.zig` and
//! `examples/firmware_riscv.zig` for the same tasks compiled for real silicon.
//!
//!     zig build demo

const std = @import("std");
const breeze = @import("breeze");
const hal = breeze.hal.host;
const Tick = breeze.Tick;
const Step = breeze.Step;

// --- events raised by "interrupts" -----------------------------------------

const EVT_UART_RX: u32 = 1 << 0;

// --- task 1: a 20 ms control loop ------------------------------------------
//
// A purely periodic task needs no sequencing, so it is a plain function with
// its state in a context struct.

const Control = struct {
    setpoint: f32 = 1.0,
    measured: f32 = 0.0,
    integral: f32 = 0.0,
    output: f32 = 0.0,
    ticks: u32 = 0,

    const kp: f32 = 0.8;
    const ki: f32 = 0.05;

    fn poll(ctx: *Control, now: Tick, events: u32) Step {
        _ = .{ now, events };

        // Stands in for "read the sensor, run the controller, write the
        // actuator". The control algorithms themselves are untouched by the
        // scheduler design; only how they are driven changes.
        const error_term = ctx.setpoint - ctx.measured;
        ctx.integral += error_term * 0.02;
        ctx.output = kp * error_term + ki * ctx.integral;
        ctx.measured += ctx.output * 0.02;

        ctx.ticks += 1;
        return .finished;
    }
};

// --- task 2: a sequenced handshake -----------------------------------------
//
// This is the case protothreads existed for: send a request, wait for an
// acknowledgement, time out, retry a bounded number of times, then give up.
//
// In C this needed `case __LINE__:` labels threaded through a `switch`. Here it
// is a comptime instruction list; the dispatch, jump table and resumable state
// are generated by the compiler.

const Entry = struct {
    at: Tick,
    what: []const u8,
};

const Handshake = struct {
    // Fields must precede declarations in a Zig container.
    prog: Program = .{},
    /// Timestamp stamped once per poll. `call` actions receive only the
    /// context, so anything they need - time included - travels in here rather
    /// than through a wider instruction signature.
    now: Tick = 0,
    attempt: u32 = 0,
    succeeded: u32 = 0,
    gave_up: u32 = 0,
    log: [24]Entry = undefined,
    log_len: usize = 0,

    /// Attempts allowed within one handshake cycle.
    const max_attempts: u32 = 3;
    const ack_timeout_ms: u32 = 50;

    fn note(ctx: *Handshake, what: []const u8) void {
        if (ctx.log_len < ctx.log.len) {
            ctx.log[ctx.log_len] = .{ .at = ctx.now, .what = what };
            ctx.log_len += 1;
        }
    }

    fn beginCycle(ctx: *Handshake) void {
        ctx.attempt = 0;
    }

    fn send(ctx: *Handshake) void {
        ctx.attempt += 1;
        note(ctx, "tx");
    }

    fn canRetry(ctx: *Handshake) bool {
        return ctx.attempt < max_attempts;
    }

    fn onSuccess(ctx: *Handshake) void {
        ctx.succeeded += 1;
        note(ctx, "ack");
        // Consume the flag. An ISR only ever sets bits; clearing is the task's
        // job, and it has to happen inside a critical section - which is
        // exactly what `clearEvents` does.
        sched.clearEvents(EVT_UART_RX);
    }

    fn onGiveUp(ctx: *Handshake) void {
        ctx.gave_up += 1;
        note(ctx, "giveup");
    }

    // Each arm ends in `jump` or `finish`, so the two can never fall into each
    // other. That is the failure this design exists to make visible: there is
    // no `switch` to drift over time, and every exit is explicit.
    const instrs = [_]breeze.Instr(Handshake){
        // 0
        .{ .call = beginCycle },
        // 1
        .{ .call = send },
        // 2: wait up to 50 ms for an ACK
        .{ .wait_event_timeout = .{ .mask = EVT_UART_RX, .timeout_ms = ack_timeout_ms } },
        // 3: ACK -> success arm at 7
        .{ .branch_event = 7 },
        // 4: no ACK, attempts remain -> send again at 1
        .{ .branch_if = .{ .pred = canRetry, .target = 1 } },
        // 5: out of attempts
        .{ .call = onGiveUp },
        // 6: leave before the success arm
        .{ .jump = 8 },
        // 7
        .{ .call = onSuccess },
        // 8
        .finish,
    };
    const Program = breeze.Program(Handshake, &instrs);

    fn poll(ctx: *Handshake, now: Tick, events: u32) Step {
        ctx.now = now;
        return ctx.prog.poll(ctx, now, events);
    }
};

// --- the superloop ---------------------------------------------------------

var control = Control{};
var handshake = Handshake{};

const Sched = breeze.Scheduler(hal.HostHal, .{
    .{ .name = "control", .period_ms = 20, .ctx = &control, .poll = Control.poll },
    .{ .name = "handshake", .period_ms = 0, .ctx = &handshake, .poll = Handshake.poll },
});

var sched = Sched.init();

/// Drive the loop for `ms` of virtual time. `ack` decides when a simulated UART
/// interrupt fires; it stands in for hardware, not for application code.
fn simulate(ms: u32, comptime ack: fn (Tick) bool) void {
    var t: Tick = 0;
    while (t < ms) : (t += 1) {
        hal.HostHal.setNow(t);
        if (ack(t)) {
            sched.events.setFromIsr(EVT_UART_RX);
        }
        sched.run();
    }
}

fn reset() void {
    hal.HostHal.reset();
    control = Control{};
    handshake = Handshake{};
    sched = Sched.init();
}

fn report(name: []const u8) void {
    std.debug.print("  {s}\n", .{name});
    std.debug.print("    succeeded={d} gave_up={d}\n", .{
        handshake.succeeded, handshake.gave_up,
    });
    std.debug.print("    trace:", .{});
    for (handshake.log[0..handshake.log_len]) |e| {
        std.debug.print(" {s}@{d}", .{ e.what, e.at });
    }
    std.debug.print("\n\n", .{});
}

fn ackAt30(t: Tick) bool {
    return t == 30;
}
fn ackAt300(t: Tick) bool {
    return t == 300;
}
fn ackEvery15(t: Tick) bool {
    return t % 15 == 0;
}

pub fn main() void {
    std.debug.print("Breeze {s} - cooperative kernel demo\n", .{breeze.version});
    std.debug.print("scheduler state per task = {d} bytes; task table lives in ROM\n", .{@sizeOf(breeze.TaskState)});
    std.debug.print("Program state = {d} bytes, independent of instruction count\n\n", .{
        @sizeOf(breeze.Program(Handshake, &Handshake.instrs)),
    });

    // --- scenario 1: one ACK arrives at t=30 ms ---------------------------
    std.debug.print("scenario 1: a single ACK at t=30ms, then silence\n", .{});
    reset();
    simulate(400, ackAt30);
    report("cycle 1 succeeds, later cycles exhaust their retries");

    // --- scenario 2: ACK always arrives too late --------------------------
    std.debug.print("scenario 2: an ACK at t=300ms, long after the 50ms window\n", .{});
    reset();
    simulate(400, ackAt300);
    report("all three attempts time out");

    // --- scenario 3: a healthy link ---------------------------------------
    std.debug.print("scenario 3: ACKs keep arriving inside the window\n", .{});
    reset();
    simulate(400, ackEvery15);
    report("steady state");

    std.debug.print("kernel health over the last run\n", .{});
    std.debug.print("  passes={d} idle_passes={d}\n", .{ sched.passes, sched.idle_passes });
    std.debug.print("  worst lateness={d} ms, grid resyncs={d}\n", .{
        sched.worstLateness(), sched.totalResyncs(),
    });
    std.debug.print("  control task ran {d} times (expect {d})\n", .{ control.ticks, 400 / 20 });
}
