/**
 * @file gen_math_corpus.c
 * @brief Prints what the C math library answers, so the Zig port can be checked
 *        against the implementation it replaces.
 *
 * ARCHITECTURE.md §8 says each migrated module is checked against the C version.
 * "Checked against" needs a definition, and the honest one is: the C code runs,
 * and its answers are committed as data that the Zig tests compare with. This
 * program produces that data.
 *
 *   gcc -std=gnu17 -Wall -Wextra -Werror tools/corpus/gen_math_corpus.c -o gen -lm
 *   ./gen > src/math/testdata/math_corpus.txt
 *
 * The output is deliberately flat text instead of a Zig literal: the fixture can
 * then be regenerated by anyone with a C compiler, without a Zig build, and a
 * diff of it is readable in review. `tools/check-c.ps1` regenerates it and fails
 * if the committed copy no longer matches, so an oracle that drifts is a red
 * build rather than a test that quietly compares against the wrong numbers.
 *
 * Values are printed with %.9g, which round-trips every `float` exactly: the
 * fixture loses nothing, so a mismatch is a real difference and not a printing
 * artefact.
 *
 * Cases are added module by module as the migration proceeds. vector is done;
 * matrix, quaternion and interpolation follow.
 */

#include <stddef.h>
#include <stdio.h>

#include "../../include/breeze/math/vector.h"

/* One printer per arity keeps `main` a readable list of cases. */
static void p2(const char* name, BreezeVector2D v) {
    printf("%s %.9g %.9g\n", name, (double)v.x, (double)v.y);
}

static void p3(const char* name, BreezeVector3D v) {
    printf("%s %.9g %.9g %.9g\n", name, (double)v.x, (double)v.y, (double)v.z);
}

static void p4(const char* name, BreezeVector4D v) {
    printf("%s %.9g %.9g %.9g %.9g\n", name,
           (double)v.x, (double)v.y, (double)v.z, (double)v.w);
}

static void pf(const char* name, float v) {
    printf("%s %.9g\n", name, (double)v);
}

static void pi(const char* name, int v) {
    printf("%s %d\n", name, v);
}

int main(void) {
    /* The header, not documentation: a reader of the fixture should be able to
     * tell where it came from without opening this file. */
    printf("# Breeze math corpus - answers produced by the C library in include/breeze/.\n");
    printf("# Generated by tools/corpus/gen_math_corpus.c; do not edit by hand.\n");
    printf("# %s\n", "format: <case> <value>...  (floats printed with %.9g, which round-trips float)");

    const BreezeVector2D a2 = {1.0f, 2.0f};
    const BreezeVector2D b2 = {3.0f, -4.0f};
    const BreezeVector3D a3 = {1.0f, 2.0f, 3.0f};
    const BreezeVector3D b3 = {-4.0f, 5.0f, 6.0f};
    const BreezeVector4D a4 = {1.0f, 2.0f, 3.0f, 4.0f};
    const BreezeVector4D b4 = {5.0f, -6.0f, 7.0f, 8.0f};
    BreezeVector2D r2;
    BreezeVector3D r3;
    BreezeVector4D r4;

    /* Layout. The Zig types are plain structs with the same fields, so pinning
     * size and alignment here is what makes "the two representations are
     * interchangeable in memory" a checked claim rather than a hope. */
    printf("vec2_layout %zu %zu\n", sizeof(BreezeVector2D), _Alignof(BreezeVector2D));
    printf("vec3_layout %zu %zu\n", sizeof(BreezeVector3D), _Alignof(BreezeVector3D));
    printf("vec4_layout %zu %zu\n", sizeof(BreezeVector4D), _Alignof(BreezeVector4D));
    pi("vec2_offset_x", (int)offsetof(BreezeVector2D, x));
    pi("vec2_offset_y", (int)offsetof(BreezeVector2D, y));
    pi("vec3_offset_z", (int)offsetof(BreezeVector3D, z));
    pi("vec4_offset_w", (int)offsetof(BreezeVector4D, w));

    /* --- 2D ------------------------------------------------------------- */
    BreezeVector2D_Init(&r2, 1.5f, -2.5f);
    p2("vec2_init", r2);

    BreezeVector2D_Add(&r2, &a2, &b2);
    p2("vec2_add", r2);

    BreezeVector2D_Subtract(&r2, &a2, &b2);
    p2("vec2_subtract", r2);

    BreezeVector2D_ScalarMultiply(&r2, &a2, -3.0f);
    p2("vec2_scalar_multiply", r2);

    pf("vec2_dot", BreezeVector2D_DotProduct(&a2, &b2));
    pf("vec2_length", BreezeVector2D_Length(&b2));

    pi("vec2_normalize_ok", BreezeVector2D_Normalize(&r2, &b2));
    p2("vec2_normalize", r2);

    /* The degenerate case: the C version refuses and leaves the out parameter
     * alone. The port has to refuse too, and say so in the type. */
    r2 = (BreezeVector2D){99.0f, 99.0f};
    pi("vec2_normalize_zero_ok", BreezeVector2D_Normalize(&r2, &(const BreezeVector2D){0.0f, 0.0f}));
    p2("vec2_normalize_zero_untouched", r2);

    /* Normalizing a vector already of length 1 must be a no-op. */
    BreezeVector2D_Normalize(&r2, &b2);
    {
        BreezeVector2D again;
        pi("vec2_normalize_twice_ok", BreezeVector2D_Normalize(&again, &r2));
        p2("vec2_normalize_twice", again);
    }

    /* --- 3D ------------------------------------------------------------- */
    BreezeVector3D_Init(&r3, 1.5f, -2.5f, 3.25f);
    p3("vec3_init", r3);

    BreezeVector3D_Add(&r3, &a3, &b3);
    p3("vec3_add", r3);

    BreezeVector3D_Subtract(&r3, &a3, &b3);
    p3("vec3_subtract", r3);

    BreezeVector3D_ScalarMultiply(&r3, &a3, 0.5f);
    p3("vec3_scalar_multiply", r3);

    pf("vec3_dot", BreezeVector3D_DotProduct(&a3, &b3));
    pf("vec3_length", BreezeVector3D_Length(&b3));

    BreezeVector3D_CrossProduct(&r3, &a3, &b3);
    p3("vec3_cross", r3);

    /* The C version documents a temporary precisely so that in-place use is
     * safe. Both spellings are captured, because the port must keep both. */
    r3 = a3;
    BreezeVector3D_CrossProduct(&r3, &r3, &b3);
    p3("vec3_cross_in_place_a", r3);

    r3 = b3;
    BreezeVector3D_CrossProduct(&r3, &a3, &r3);
    p3("vec3_cross_in_place_b", r3);

    /* Cross product of parallel vectors is exactly zero. */
    BreezeVector3D_CrossProduct(&r3, &a3, &a3);
    p3("vec3_cross_self", r3);

    pi("vec3_normalize_ok", BreezeVector3D_Normalize(&r3, &b3));
    p3("vec3_normalize", r3);

    r3 = (BreezeVector3D){99.0f, 99.0f, 99.0f};
    pi("vec3_normalize_zero_ok", BreezeVector3D_Normalize(&r3, &(const BreezeVector3D){0.0f, 0.0f, 0.0f}));
    p3("vec3_normalize_zero_untouched", r3);

    /* Just under and just over the 1e-6 threshold the C code uses. This is the
     * boundary the port must copy rather than "improve": it is a contract the
     * callers already rely on. */
    pi("vec3_normalize_tiny_ok", BreezeVector3D_Normalize(&r3, &(const BreezeVector3D){1.0e-7f, 0.0f, 0.0f}));
    pi("vec3_normalize_just_above_ok", BreezeVector3D_Normalize(&r3, &(const BreezeVector3D){1.0e-3f, 0.0f, 0.0f}));

    /* --- 4D ------------------------------------------------------------- */
    BreezeVector4D_Init(&r4, 1.0f, 2.0f, 3.0f, 4.0f);
    p4("vec4_init", r4);

    BreezeVector4D_Add(&r4, &a4, &b4);
    p4("vec4_add", r4);

    BreezeVector4D_Subtract(&r4, &a4, &b4);
    p4("vec4_subtract", r4);

    BreezeVector4D_ScalarMultiply(&r4, &a4, 2.5f);
    p4("vec4_scalar_multiply", r4);

    pf("vec4_dot", BreezeVector4D_DotProduct(&a4, &b4));
    pf("vec4_length", BreezeVector4D_Length(&b4));

    pi("vec4_normalize_ok", BreezeVector4D_Normalize(&r4, &b4));
    p4("vec4_normalize", r4);

    return 0;
}
