/**
 * @file gen_math_corpus.c
 * @brief Prints what the C math library answers, so the Zig port can be checked
 *        against the implementation it replaces.
 *
 * ARCHITECTURE.md §8 says each migrated module is checked against the C version.
 * "Checked against" needs a definition, and the honest one is: the C code runs,
 * and its answers are committed as data that the Zig tests compare with. This
 * program produces that data.
 *
 *   gcc -std=gnu17 -Wall -Wextra -Werror tools/corpus/gen_math_corpus.c -o gen -lm
 *   ./gen > src/math/testdata/math_corpus.txt
 *
 * The output is deliberately flat text instead of a Zig literal: the fixture can
 * then be regenerated by anyone with a C compiler, without a Zig build, and a
 * diff of it is readable in review. `tools/check-c.ps1` regenerates it and fails
 * if the committed copy no longer matches, so an oracle that drifts is a red
 * build rather than a test that quietly compares against the wrong numbers.
 *
 * Values are printed with %.9g, which round-trips every `float` exactly: the
 * fixture loses nothing, so a mismatch is a real difference and not a printing
 * artefact.
 *
 * Cases are added module by module as the migration proceeds; vector, matrix,
 * quaternion and interpolation are covered, and the filters are being added.
 *
 * Stateful things (the filters) get one case per *run*: the values are the
 * outputs in order, so a scenario is one line rather than one line per step.
 */

#include <math.h>
#include <stddef.h>
#include <stdio.h>
#include <string.h>

#include "../../include/breeze/filter/complementary_filter.h"
#include "../../include/breeze/filter/high_pass_filter.h"
#include "../../include/breeze/filter/kalman_filter.h"
#include "../../include/breeze/filter/low_pass_filter.h"
#include "../../include/breeze/filter/median_filter.h"
#include "../../include/breeze/math/interpolation.h"
#include "../../include/breeze/math/matrix.h"
#include "../../include/breeze/math/quaternion.h"
#include "../../include/breeze/math/vector.h"

/* One printer per arity keeps `main` a readable list of cases. */
static void p2(const char* name, BreezeVector2D v) {
    printf("%s %.9g %.9g\n", name, (double)v.x, (double)v.y);
}

static void p3(const char* name, BreezeVector3D v) {
    printf("%s %.9g %.9g %.9g\n", name, (double)v.x, (double)v.y, (double)v.z);
}

static void p4(const char* name, BreezeVector4D v) {
    printf("%s %.9g %.9g %.9g %.9g\n", name,
           (double)v.x, (double)v.y, (double)v.z, (double)v.w);
}

static void pf(const char* name, float v) {
    printf("%s %.9g\n", name, (double)v);
}

static void pi(const char* name, int v) {
    printf("%s %d\n", name, v);
}

static void pq(const char* name, const BreezeQuaternion* q) {
    printf("%s %.9g %.9g %.9g %.9g\n", name,
           (double)q->w, (double)q->x, (double)q->y, (double)q->z);
}

static void p3f(const char* name, float a, float b, float c) {
    printf("%s %.9g %.9g %.9g\n", name, (double)a, (double)b, (double)c);
}

/* A run of coefficients. The C spline never writes a[n-1], b[n-1] or d[n-1] -
 * `Evaluate` cannot reach them - so only the initialised range is printed here,
 * and the port's arrays are sized to exactly that range. */
static void pvals(const char* name, const float* values, int n) {
    int i;
    printf("%s", name);
    for (i = 0; i < n; i++) printf(" %.9g", (double)values[i]);
    putchar('\n');
}

static void pbp(const char* name, const BreezeBezierPoint* p) {
    printf("%s %.9g %.9g\n", name, (double)p->x, (double)p->y);
}

/* Image buffers: bytes, printed as integers. They parse as floats on the Zig
 * side, which is all the comparison needs - and printing them as integers keeps
 * a byte buffer readable in the fixture. */
static void pbytes(const char* name, const unsigned char* bytes, int n) {
    int i;
    printf("%s", name);
    for (i = 0; i < n; i++) printf(" %d", (int)bytes[i]);
    putchar('\n');
}

/* A matrix prints its *used* region row-major, and the shape lives in the case
 * name (`matrix_add_2x2`) rather than in the data. The Zig type carries its
 * shape at compile time, so printing rows and cols as values would be comparing
 * a compile-time fact against itself; what needs checking is the arithmetic. */
static void pm(const char* name, const BreezeMatrix* m) {
    int i, j;
    printf("%s", name);
    for (i = 0; i < m->rows; i++) {
        for (j = 0; j < m->cols; j++) printf(" %.9g", (double)m->data[i][j]);
    }
    putchar('\n');
}

/* Row-major fill, so each case reads as the matrix it is about. */
static void setm(BreezeMatrix* m, int rows, int cols, const float* values) {
    int i, j, k = 0;
    BreezeMatrix_Init(m, rows, cols);
    for (i = 0; i < rows; i++) {
        for (j = 0; j < cols; j++) m->data[i][j] = values[k++];
    }
}

int main(void) {
    /* The header, not documentation: a reader of the fixture should be able to
     * tell where it came from without opening this file. */
    printf("# Breeze math corpus - answers produced by the C library in include/breeze/.\n");
    printf("# Generated by tools/corpus/gen_math_corpus.c; do not edit by hand.\n");
    printf("# %s\n", "format: <case> <value>...  (floats printed with %.9g, which round-trips float)");

    const BreezeVector2D a2 = {1.0f, 2.0f};
    const BreezeVector2D b2 = {3.0f, -4.0f};
    const BreezeVector3D a3 = {1.0f, 2.0f, 3.0f};
    const BreezeVector3D b3 = {-4.0f, 5.0f, 6.0f};
    const BreezeVector4D a4 = {1.0f, 2.0f, 3.0f, 4.0f};
    const BreezeVector4D b4 = {5.0f, -6.0f, 7.0f, 8.0f};
    BreezeVector2D r2;
    BreezeVector3D r3;
    BreezeVector4D r4;

    /* Layout. The Zig types are plain structs with the same fields, so pinning
     * size and alignment here is what makes "the two representations are
     * interchangeable in memory" a checked claim rather than a hope. */
    printf("vec2_layout %zu %zu\n", sizeof(BreezeVector2D), _Alignof(BreezeVector2D));
    printf("vec3_layout %zu %zu\n", sizeof(BreezeVector3D), _Alignof(BreezeVector3D));
    printf("vec4_layout %zu %zu\n", sizeof(BreezeVector4D), _Alignof(BreezeVector4D));
    pi("vec2_offset_x", (int)offsetof(BreezeVector2D, x));
    pi("vec2_offset_y", (int)offsetof(BreezeVector2D, y));
    pi("vec3_offset_z", (int)offsetof(BreezeVector3D, z));
    pi("vec4_offset_w", (int)offsetof(BreezeVector4D, w));

    /* --- 2D ------------------------------------------------------------- */
    BreezeVector2D_Init(&r2, 1.5f, -2.5f);
    p2("vec2_init", r2);

    BreezeVector2D_Add(&r2, &a2, &b2);
    p2("vec2_add", r2);

    BreezeVector2D_Subtract(&r2, &a2, &b2);
    p2("vec2_subtract", r2);

    BreezeVector2D_ScalarMultiply(&r2, &a2, -3.0f);
    p2("vec2_scalar_multiply", r2);

    pf("vec2_dot", BreezeVector2D_DotProduct(&a2, &b2));
    pf("vec2_length", BreezeVector2D_Length(&b2));

    pi("vec2_normalize_ok", BreezeVector2D_Normalize(&r2, &b2));
    p2("vec2_normalize", r2);

    /* The degenerate case: the C version refuses and leaves the out parameter
     * alone. The port has to refuse too, and say so in the type. */
    r2 = (BreezeVector2D){99.0f, 99.0f};
    pi("vec2_normalize_zero_ok", BreezeVector2D_Normalize(&r2, &(const BreezeVector2D){0.0f, 0.0f}));
    p2("vec2_normalize_zero_untouched", r2);

    /* Normalizing a vector already of length 1 must be a no-op. */
    BreezeVector2D_Normalize(&r2, &b2);
    {
        BreezeVector2D again;
        pi("vec2_normalize_twice_ok", BreezeVector2D_Normalize(&again, &r2));
        p2("vec2_normalize_twice", again);
    }

    /* --- 3D ------------------------------------------------------------- */
    BreezeVector3D_Init(&r3, 1.5f, -2.5f, 3.25f);
    p3("vec3_init", r3);

    BreezeVector3D_Add(&r3, &a3, &b3);
    p3("vec3_add", r3);

    BreezeVector3D_Subtract(&r3, &a3, &b3);
    p3("vec3_subtract", r3);

    BreezeVector3D_ScalarMultiply(&r3, &a3, 0.5f);
    p3("vec3_scalar_multiply", r3);

    pf("vec3_dot", BreezeVector3D_DotProduct(&a3, &b3));
    pf("vec3_length", BreezeVector3D_Length(&b3));

    BreezeVector3D_CrossProduct(&r3, &a3, &b3);
    p3("vec3_cross", r3);

    /* The C version documents a temporary precisely so that in-place use is
     * safe. Both spellings are captured, because the port must keep both. */
    r3 = a3;
    BreezeVector3D_CrossProduct(&r3, &r3, &b3);
    p3("vec3_cross_in_place_a", r3);

    r3 = b3;
    BreezeVector3D_CrossProduct(&r3, &a3, &r3);
    p3("vec3_cross_in_place_b", r3);

    /* Cross product of parallel vectors is exactly zero. */
    BreezeVector3D_CrossProduct(&r3, &a3, &a3);
    p3("vec3_cross_self", r3);

    pi("vec3_normalize_ok", BreezeVector3D_Normalize(&r3, &b3));
    p3("vec3_normalize", r3);

    r3 = (BreezeVector3D){99.0f, 99.0f, 99.0f};
    pi("vec3_normalize_zero_ok", BreezeVector3D_Normalize(&r3, &(const BreezeVector3D){0.0f, 0.0f, 0.0f}));
    p3("vec3_normalize_zero_untouched", r3);

    /* Just under and just over the 1e-6 threshold the C code uses. This is the
     * boundary the port must copy rather than "improve": it is a contract the
     * callers already rely on. */
    pi("vec3_normalize_tiny_ok", BreezeVector3D_Normalize(&r3, &(const BreezeVector3D){1.0e-7f, 0.0f, 0.0f}));
    pi("vec3_normalize_just_above_ok", BreezeVector3D_Normalize(&r3, &(const BreezeVector3D){1.0e-3f, 0.0f, 0.0f}));

    /* --- 4D ------------------------------------------------------------- */
    BreezeVector4D_Init(&r4, 1.0f, 2.0f, 3.0f, 4.0f);
    p4("vec4_init", r4);

    BreezeVector4D_Add(&r4, &a4, &b4);
    p4("vec4_add", r4);

    BreezeVector4D_Subtract(&r4, &a4, &b4);
    p4("vec4_subtract", r4);

    BreezeVector4D_ScalarMultiply(&r4, &a4, 2.5f);
    p4("vec4_scalar_multiply", r4);

    pf("vec4_dot", BreezeVector4D_DotProduct(&a4, &b4));
    pf("vec4_length", BreezeVector4D_Length(&b4));

    pi("vec4_normalize_ok", BreezeVector4D_Normalize(&r4, &b4));
    p4("vec4_normalize", r4);

    /* --- matrix ---------------------------------------------------------- */
    BreezeMatrix ma, mr;

    /* Determinant 1, and its inverse is the textbook integer matrix
     * [[-24,18,5],[20,-15,-4],[-5,4,1]] - exact in float, so a mismatch here is
     * the port's fault and not rounding. */
    const float b3v[] = {1.0f, 2.0f, 3.0f, 0.0f, 1.0f, 4.0f, 5.0f, 6.0f, 0.0f};
    BreezeMatrix b3m, four4;
    setm(&b3m, 3, 3, b3v);
    setm(&four4, 4, 4, (const float[]){1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f,
                                       0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f});

    printf("matrix_layout %zu %zu\n", sizeof ma, _Alignof(BreezeMatrix));
    printf("matrix_data_bytes %zu\n", sizeof ma.data);

    /* Init zeroes only the used region - the storage beyond it is left alone,
     * which is a property the Zig type cannot have because it has no storage
     * beyond its shape. Captured here so the difference is on the record. */
    BreezeMatrix_Init(&ma, 2, 3);
    pm("matrix_init_2x3", &ma);

    BreezeMatrix_Init(&ma, 3, 3);
    BreezeMatrix_SetIdentity(&ma);
    pm("matrix_identity_3x3", &ma);

    /* Non-square identity: the C code fills ones only out to min(rows, cols). */
    BreezeMatrix_Init(&ma, 2, 3);
    BreezeMatrix_SetIdentity(&ma);
    pm("matrix_identity_2x3", &ma);

    BreezeMatrix_Init(&ma, 2, 2);
    BreezeMatrix_SetElement(&ma, 0, 1, 7.5f);
    pf("matrix_get_element", BreezeMatrix_GetElement(&ma, 0, 1));
    pf("matrix_get_out_of_range", BreezeMatrix_GetElement(&ma, 5, 0));
    pm("matrix_set_get_2x2", &ma);
    BreezeMatrix_SetElement(&ma, 9, 9, 1.0f); /* silently ignored */
    pm("matrix_set_out_of_range_2x2", &ma);

    const float a2v[] = {4.0f, 7.0f, 2.0f, 6.0f};
    const float b2v[] = {1.0f, 2.0f, 3.0f, 4.0f};
    const float singv[] = {1.0f, 2.0f, 2.0f, 4.0f};
    BreezeMatrix ma2, mb2, msing;
    setm(&ma2, 2, 2, a2v);
    setm(&mb2, 2, 2, b2v);
    setm(&msing, 2, 2, singv);

    pi("matrix_add_2x2_ok", BreezeMatrix_Add(&mr, &ma2, &mb2));
    pm("matrix_add_2x2", &mr);

    pi("matrix_subtract_2x2_ok", BreezeMatrix_Subtract(&mr, &ma2, &mb2));
    pm("matrix_subtract_2x2", &mr);

    pi("matrix_multiply_2x2_ok", BreezeMatrix_Multiply(&mr, &ma2, &mb2));
    pm("matrix_multiply_2x2", &mr);

    /* In place, which the C version supports on purpose (it multiplies into a
     * temporary precisely so that result may alias an input). */
    setm(&mr, 2, 2, a2v);
    pi("matrix_multiply_in_place_ok", BreezeMatrix_Multiply(&mr, &mr, &mb2));
    pm("matrix_multiply_in_place_2x2", &mr);

    const float pv[] = {1.0f, 2.0f, 3.0f, 4.0f, 5.0f, 6.0f};    /* 2x3 */
    const float qv[] = {7.0f, 8.0f, 9.0f, 10.0f, 11.0f, 12.0f};  /* 3x2 */
    BreezeMatrix p, q, r;
    setm(&p, 2, 3, pv);
    setm(&q, 3, 2, qv);

    pi("matrix_multiply_2x3_3x2_ok", BreezeMatrix_Multiply(&r, &p, &q));
    pm("matrix_multiply_2x3_3x2", &r);

    /* Inner dimensions disagree: the C version refuses and says so in its
     * return value. The Zig signature makes this unrepresentable. */
    setm(&r, 2, 2, b2v);
    pi("matrix_multiply_mismatch_ok", BreezeMatrix_Multiply(&r, &ma2, &q));

    const float sv[] = {2.0f, -1.0f, 0.5f, 3.0f, 4.0f, -2.0f}; /* 3x2 */
    BreezeMatrix s;
    setm(&s, 3, 2, sv);
    BreezeMatrix_ScalarMultiply(&r, &s, -1.5f);
    pm("matrix_scalar_multiply_3x2", &r);

    BreezeMatrix_Transpose(&r, &p);
    pm("matrix_transpose_2x3", &r);

    /* In place again: transpose is where aliasing is easiest to get wrong. */
    setm(&r, 3, 3, (const float[]){1.0f, 2.0f, 3.0f, 4.0f, 5.0f, 6.0f, 7.0f, 8.0f, 9.0f});
    BreezeMatrix_Transpose(&r, &r);
    pm("matrix_transpose_in_place_3x3", &r);

    pf("matrix_det_2x2", BreezeMatrix_Determinant2x2(&ma2));
    pf("matrix_det_3x3", BreezeMatrix_Determinant3x3(&b3m));
    pf("matrix_det_dispatch_2x2", BreezeMatrix_Determinant(&ma2));
    pf("matrix_det_dispatch_3x3", BreezeMatrix_Determinant(&b3m));
    /* Not square: refused. */
    pf("matrix_det_nonsquare", BreezeMatrix_Determinant(&p));
    /* Square but unsupported: the C code returns 0 rather than computing it.
     * The port makes this a compile error instead, so no Zig case reads this. */
    pf("matrix_det_4x4", BreezeMatrix_Determinant(&four4));

    pi("matrix_inverse_2x2_ok", BreezeMatrix_Inverse2x2(&mr, &ma2));
    pm("matrix_inverse_2x2", &mr);

    pi("matrix_inverse_3x3_ok", BreezeMatrix_Inverse3x3(&mr, &b3m));
    pm("matrix_inverse_3x3", &mr);

    pi("matrix_inverse_dispatch_2x2_ok", BreezeMatrix_Inverse(&mr, &ma2));
    pm("matrix_inverse_dispatch_2x2", &mr);

    pi("matrix_inverse_4x4_ok", BreezeMatrix_Inverse(&mr, &four4));

    /* Singular: refused, and - because the refusal happens before the write -
     * the caller's result is untouched. The Zig port returns an error instead,
     * so what is checked there is the error, not the untouched buffer. */
    setm(&mr, 2, 2, b2v);
    pi("matrix_inverse_singular_ok", BreezeMatrix_Inverse2x2(&mr, &msing));
    pm("matrix_inverse_singular_untouched", &mr);

    /* --- quaternion ------------------------------------------------------ */
    BreezeQuaternion qa, qb, qr;
    float qr_roll, qr_pitch, qr_yaw;

    printf("quat_layout %zu %zu\n", sizeof qa, _Alignof(BreezeQuaternion));

    BreezeQuaternion_SetIdentity(&qa);
    pq("quat_identity", &qa);

    BreezeQuaternion_Init(&qa, 1.5f, -2.5f, 3.25f, -4.75f);
    pq("quat_init", &qa);

    /* Trigonometry enters here, so these are the cases where a libm difference
     * between the two implementations could show up as a last-bit disagreement.
     * The comparison tolerance exists for them. */
    BreezeQuaternion_FromEulerZYX(&qa, 0.3f, -0.4f, 1.1f);
    pq("quat_from_euler_zyx", &qa);

    BreezeQuaternion_FromEulerZYX(&qa, 0.0f, 0.0f, 0.0f);
    pq("quat_from_euler_zyx_zero", &qa);

    BreezeQuaternion_FromEulerZYX(&qa, 0.3f, -0.4f, 1.1f);
    BreezeQuaternion_ToEulerZYX(&qa, &qr_roll, &qr_pitch, &qr_yaw);
    p3f("quat_euler_roundtrip", qr_roll, qr_pitch, qr_yaw);

    /* pitch = +pi/2 is the gimbal-lock branch, where the C code sets roll to 0
     * by convention and takes yaw from a different formula. */
    BreezeQuaternion_FromEulerZYX(&qa, 0.3f, (float)(M_PI / 2.0), 1.1f);
    pq("quat_from_euler_zyx_gimbal", &qa);
    BreezeQuaternion_ToEulerZYX(&qa, &qr_roll, &qr_pitch, &qr_yaw);
    p3f("quat_euler_gimbal", qr_roll, qr_pitch, qr_yaw);

    const BreezeVector3D axis_xyz = {1.0f, 2.0f, 2.0f};
    BreezeQuaternion_FromAxisAngle(&qa, &axis_xyz, 0.7f);
    pq("quat_from_axis_angle", &qa);

    /* A degenerate axis: the C version falls back to the identity rather than
     * failing, because "rotate by any angle about no axis" has an answer. */
    BreezeQuaternion_FromAxisAngle(&qa, &(const BreezeVector3D){0.0f, 0.0f, 0.0f}, 0.7f);
    pq("quat_from_axis_angle_degenerate", &qa);

    const BreezeVector3D axis_x = {1.0f, 0.0f, 0.0f};
    BreezeQuaternion_FromAxisAngle(&qa, &axis_x, (float)(M_PI / 3.0));
    pq("quat_from_axis_angle_x", &qa);

    BreezeQuaternion_Init(&qa, 1.5f, -2.5f, 3.25f, -4.75f);
    pf("quat_magnitude", BreezeQuaternion_Magnitude(&qa));

    pi("quat_normalize_ok", BreezeQuaternion_Normalize(&qr, &qa));
    pq("quat_normalize", &qr);

    /* Note the threshold asymmetry, which the port has to keep: Normalize
     * compares the *magnitude* against 1e-6 while Inverse compares the squared
     * magnitude against the same number. A quaternion of magnitude 1e-4 is
     * therefore accepted by one and refused by the other. */
    pq("quat_normalize_degenerate_untouched", &(const BreezeQuaternion){9.0f, 9.0f, 9.0f, 9.0f});
    pi("quat_normalize_degenerate_ok", BreezeQuaternion_Normalize(&(BreezeQuaternion){9.0f, 9.0f, 9.0f, 9.0f}, &(const BreezeQuaternion){1.0e-7f, 0.0f, 0.0f, 0.0f}));
    pi("quat_inverse_degenerate_ok", BreezeQuaternion_Inverse(&(BreezeQuaternion){9.0f, 9.0f, 9.0f, 9.0f}, &(const BreezeQuaternion){1.0e-7f, 0.0f, 0.0f, 0.0f}));
    /* Magnitude 1e-4: Normalize accepts (1e-4 >= 1e-6), Inverse refuses
     * (1e-8 < 1e-6). Both statuses are captured so the asymmetry is pinned. */
    pi("quat_normalize_boundary_ok", BreezeQuaternion_Normalize(&(BreezeQuaternion){9.0f, 9.0f, 9.0f, 9.0f}, &(const BreezeQuaternion){1.0e-4f, 0.0f, 0.0f, 0.0f}));
    pi("quat_inverse_boundary_ok", BreezeQuaternion_Inverse(&(BreezeQuaternion){9.0f, 9.0f, 9.0f, 9.0f}, &(const BreezeQuaternion){1.0e-4f, 0.0f, 0.0f, 0.0f}));

    BreezeQuaternion_Init(&qa, 1.5f, -2.5f, 3.25f, -4.75f);
    BreezeQuaternion_Conjugate(&qr, &qa);
    pq("quat_conjugate", &qr);

    pi("quat_inverse_ok", BreezeQuaternion_Inverse(&qr, &qa));
    pq("quat_inverse", &qr);

    /* 90 degrees about z, then 90 degrees about x: two unit quaternions whose
     * product is another one, and whose components are exactly representable
     * halves of a square root - no special values, no gimbal lock. */
    const BreezeVector3D axis_z = {0.0f, 0.0f, 1.0f};
    BreezeQuaternion_FromAxisAngle(&qa, &axis_z, (float)(M_PI / 2.0));
    BreezeQuaternion_FromAxisAngle(&qb, &axis_x, (float)(M_PI / 2.0));
    pq("quat_z90", &qa);
    pq("quat_x90", &qb);

    BreezeQuaternion_Multiply(&qr, &qa, &qb);
    pq("quat_multiply", &qr);

    /* The in-place spelling the C version supports by multiplying into a
     * temporary. */
    BreezeQuaternion q_in_place = qa;
    BreezeQuaternion_Multiply(&q_in_place, &q_in_place, &qb);
    pq("quat_multiply_in_place", &q_in_place);

    const BreezeVector3D vx = {1.0f, 0.0f, 0.0f};
    BreezeVector3D vr;
    BreezeQuaternion_RotateVector(&vr, &qa, &vx);
    p3("quat_rotate", vr);

    /* Result aliasing the input vector: the C version writes only at the end,
     * so this is safe there too. */
    vr = vx;
    BreezeQuaternion_RotateVector(&vr, &qa, &vr);
    p3("quat_rotate_in_place", vr);

    BreezeQuaternion_SetIdentity(&qb);
    BreezeQuaternion_Slerp(&qr, &qb, &qa, 0.0f);
    pq("quat_slerp_t0", &qr);
    BreezeQuaternion_Slerp(&qr, &qb, &qa, 0.25f);
    pq("quat_slerp_t025", &qr);
    BreezeQuaternion_Slerp(&qr, &qb, &qa, 0.5f);
    pq("quat_slerp_t05", &qr);
    BreezeQuaternion_Slerp(&qr, &qb, &qa, 1.0f);
    pq("quat_slerp_t1", &qr);
    /* t outside [0, 1] is clamped, not extrapolated. */
    BreezeQuaternion_Slerp(&qr, &qb, &qa, 1.5f);
    pq("quat_slerp_clamped", &qr);

    /* Nearly identical inputs take the linear branch (dot > 0.9999). */
    BreezeQuaternion_Slerp(&qr, &qb, &qb, 0.5f);
    pq("quat_slerp_linear_branch", &qr);

    /* Negative dot: the C version negates b to take the short way round. */
    BreezeQuaternion_Init(&qb, -1.0f, 0.0f, 0.0f, 0.0f);
    BreezeQuaternion_Slerp(&qr, &qa, &qb, 0.5f);
    pq("quat_slerp_negative_dot", &qr);

    /* --- interpolation --------------------------------------------------- */
    /* The three scalar curves. Cosine is the one that brings cosf in; Hermite
     * takes the neighbouring points and two shape parameters. */
    pf("interp_linear", BreezeInterpolation_Linear(0.0f, 0.0f, 2.0f, 4.0f, 0.5f));
    /* x0 and x1 within 1e-6 of each other: the C code answers with the midpoint
     * rather than dividing by (almost) zero. */
    pf("interp_linear_degenerate", BreezeInterpolation_Linear(1.0f, 3.0f, 1.0f + 1.0e-7f, 7.0f, 5.0f));

    pf("interp_cosine_mu0", BreezeInterpolation_Cosine(0.0f, 10.0f, 0.0f));
    pf("interp_cosine_mu025", BreezeInterpolation_Cosine(0.0f, 10.0f, 0.25f));
    pf("interp_cosine_mu05", BreezeInterpolation_Cosine(0.0f, 10.0f, 0.5f));
    pf("interp_cosine_mu1", BreezeInterpolation_Cosine(0.0f, 10.0f, 1.0f));

    pf("interp_hermite", BreezeInterpolation_CubicHermite(0.0f, 1.0f, 2.0f, 3.0f, 0.5f, 0.0f, 0.0f));
    pf("interp_hermite_tension_bias", BreezeInterpolation_CubicHermite(0.0f, 1.0f, 2.0f, 3.0f, 0.5f, 0.3f, 0.2f));

    float spx[] = {0.0f, 1.0f, 2.0f, 3.0f, 4.0f};
    float spy[] = {0.0f, 1.0f, 0.0f, 1.0f, 0.0f};
    BreezeSplineInterpolation sp;

    pi("spline_init_ok", BreezeSplineInterpolation_Init(&sp, spx, spy, 5, 0));
    pvals("spline_a", sp.a, 4);
    pvals("spline_b", sp.b, 4);
    pvals("spline_c", sp.c, 5);
    pvals("spline_d", sp.d, 4);

    /* Evaluate clamps outside the knot range and lands exactly on y at a knot. */
    pf("spline_eval_below_range", BreezeSplineInterpolation_Evaluate(&sp, -1.0f));
    pf("spline_eval_at_knot0", BreezeSplineInterpolation_Evaluate(&sp, 0.0f));
    pf("spline_eval_at_knot2", BreezeSplineInterpolation_Evaluate(&sp, 2.0f));
    pf("spline_eval_between", BreezeSplineInterpolation_Evaluate(&sp, 1.5f));
    pf("spline_eval_above_range", BreezeSplineInterpolation_Evaluate(&sp, 9.0f));
    BreezeSplineInterpolation_Free(&sp);

    /* Collinear knots: a natural cubic spline through them is that line exactly,
     * so this case doubles as a check that is independent of the oracle. */
    float linx[] = {0.0f, 1.0f, 2.0f, 3.0f};
    float liny[] = {1.0f, 3.0f, 5.0f, 7.0f};
    pi("spline_init_linear_ok", BreezeSplineInterpolation_Init(&sp, linx, liny, 4, 0));
    pf("spline_linear_at_0p5", BreezeSplineInterpolation_Evaluate(&sp, 0.5f));
    pf("spline_linear_at_2p5", BreezeSplineInterpolation_Evaluate(&sp, 2.5f));
    BreezeSplineInterpolation_Free(&sp);

    /* Knots that do not strictly increase: refused, and the C reason is a
     * division that would be by (almost) zero. */
    float badx[] = {0.0f, 1.0f, 1.0f, 3.0f};
    float bady[] = {0.0f, 1.0f, 2.0f, 3.0f};
    pi("spline_init_not_increasing_ok", BreezeSplineInterpolation_Init(&sp, badx, bady, 4, 0));

    pi("spline_init_too_few_ok", BreezeSplineInterpolation_Init(&sp, spx, spy, 1, 0));

    /* Bezier: pure polynomial evaluation, no solver. */
    BreezeBezierPoint bp0 = {0.0f, 0.0f};
    BreezeBezierPoint bp1 = {1.0f, 3.0f};
    BreezeBezierPoint bp2 = {4.0f, 3.0f};
    BreezeBezierPoint bp3 = {5.0f, 0.0f};
    BreezeBezierPoint bp;

    printf("bezier_layout %zu %zu\n", sizeof bp0, _Alignof(BreezeBezierPoint));

    BreezeBezierCurve_Quadratic(&bp0, &bp1, &bp2, 0.5f, &bp);
    pbp("bezier_quadratic_t05", &bp);
    BreezeBezierCurve_Quadratic(&bp0, &bp1, &bp2, 0.0f, &bp);
    pbp("bezier_quadratic_t0", &bp);

    BreezeBezierCurve_Cubic(&bp0, &bp1, &bp2, &bp3, 0.25f, &bp);
    pbp("bezier_cubic_t025", &bp);
    BreezeBezierCurve_Cubic(&bp0, &bp1, &bp2, &bp3, 0.5f, &bp);
    pbp("bezier_cubic_t05", &bp);
    BreezeBezierCurve_Cubic(&bp0, &bp1, &bp2, &bp3, 1.0f, &bp);
    pbp("bezier_cubic_t1", &bp);

    /* --- filters: the three recursive scalar ones ------------------------ */
    /* Each `*_run` case is one scenario: the inputs are fixed here, and the
     * values are the outputs in the order they came out. */
    const float steps[] = {12.0f, 13.0f, 11.0f, 18.0f, 6.0f};
    float run[8];
    int step_i;

    BreezeLowPassFilter lp;
    BreezeEWMAFilter ew;
    BreezeHighPassFilter hp;
    BreezeDCBlocker dcb;
    BreezeComplementaryFilter cf;

    BreezeLowPassFilter_Init(&lp, 0.25f, 10.0f);
    pf("lowpass_alpha_init", lp.alpha);
    pf("lowpass_prev_output_init", lp.prev_output);
    for (step_i = 0; step_i < 5; step_i++) run[step_i] = BreezeLowPassFilter_Update(&lp, steps[step_i]);
    pvals("lowpass_run", run, 5);

    /* alpha is clamped on the way in, in every entry point that takes one. */
    BreezeLowPassFilter_Init(&lp, -1.0f, 0.0f);
    pf("lowpass_alpha_clamped_low", lp.alpha);
    BreezeLowPassFilter_Init(&lp, 2.0f, 0.0f);
    pf("lowpass_alpha_clamped_high", lp.alpha);

    /* Note the direction of this formula: sample time over the sum. The high
     * pass version below divides the other way round. */
    BreezeLowPassFilter_InitWithTimeConstant(&lp, 0.5f, 0.1f, 0.0f);
    pf("lowpass_alpha_time_constant", lp.alpha);

    BreezeLowPassFilter_Init(&lp, 0.25f, 0.0f);
    BreezeLowPassFilter_SetAlpha(&lp, 0.5f);
    pf("lowpass_alpha_set", lp.alpha);
    BreezeLowPassFilter_SetTimeConstant(&lp, 0.5f, 0.5f);
    pf("lowpass_alpha_set_time_constant", lp.alpha);

    /* An invalid time constant is a silent no-op in C: nothing about the filter
     * changes, including its previous output. Captured so the port'step_i decision to
     * report an error instead is a documented difference and not a guess. */
    BreezeLowPassFilter_Init(&lp, 0.25f, 10.0f);
    BreezeLowPassFilter_InitWithTimeConstant(&lp, -1.0f, 0.1f, 99.0f);
    pf("lowpass_alpha_invalid_tc_unchanged", lp.alpha);
    pf("lowpass_prev_output_invalid_tc_unchanged", lp.prev_output);
    BreezeLowPassFilter_SetTimeConstant(&lp, 0.0f, 0.1f);
    pf("lowpass_alpha_invalid_set_tc_unchanged", lp.alpha);

    /* A zero-initialised filter has never been initialised, and the first update
     * passes its input straight through. */
    BreezeLowPassFilter lp_fresh = {0.0f, 0.0f, 0};
    pf("lowpass_first_update_uninitialised", BreezeLowPassFilter_Update(&lp_fresh, 7.5f));
    BreezeEWMAFilter ew_fresh = {0.0f, 0.0f, 0};
    pf("ewma_first_update_uninitialised", BreezeEWMAFilter_Update(&ew_fresh, 7.5f));

    BreezeLowPassFilter_Init(&lp, 0.5f, 0.0f);
    BreezeLowPassFilter_Reset(&lp, 4.0f);
    pf("lowpass_reset_then_update", BreezeLowPassFilter_Update(&lp, 8.0f));

    BreezeEWMAFilter_Init(&ew, 0.25f, 2.0f);
    pf("ewma_alpha_init", ew.alpha);
    pf("ewma_avg_init", ew.avg);
    for (step_i = 0; step_i < 5; step_i++) run[step_i] = BreezeEWMAFilter_Update(&ew, steps[step_i]);
    pvals("ewma_run", run, 5);
    BreezeEWMAFilter_Reset(&ew, 3.0f);
    pf("ewma_reset_then_update", BreezeEWMAFilter_Update(&ew, 9.0f));

    /* High pass starts uninitialised even after Init - the alpha entry points
     * deliberately leave `initialized` at zero. */
    BreezeHighPassFilter_Init(&hp, 0.25f);
    pf("highpass_alpha_init", hp.alpha);
    pf("highpass_initialised_after_init", (float)hp.initialized);
    for (step_i = 0; step_i < 5; step_i++) run[step_i] = BreezeHighPassFilter_Update(&hp, steps[step_i]);
    pvals("highpass_run", run, 5);

    BreezeHighPassFilter_InitWithTimeConstant(&hp, 0.5f, 0.1f);
    pf("highpass_alpha_time_constant", hp.alpha);

    BreezeHighPassFilter_InitWithTimeConstant(&hp, -1.0f, 0.1f);
    pf("highpass_alpha_invalid_tc_unchanged", hp.alpha);

    BreezeHighPassFilter_Init(&hp, 0.25f);
    BreezeHighPassFilter_Reset(&hp, 5.0f);
    pf("highpass_reset_then_update", BreezeHighPassFilter_Update(&hp, 5.0f));

    BreezeDCBlocker_Init(&dcb, 0.1f);
    pf("dcblock_alpha_init", dcb.alpha);
    for (step_i = 0; step_i < 5; step_i++) run[step_i] = BreezeDCBlocker_Update(&dcb, steps[step_i]);
    pvals("dcblock_run", run, 5);
    BreezeDCBlocker_Reset(&dcb, 5.0f);
    pf("dcblock_reset_then_update", BreezeDCBlocker_Update(&dcb, 5.0f));

    /* Complementary: the roll and pitch outputs of the same run. */
    const float gx[] = {0.01f, 0.02f, -0.01f, 0.03f, 0.0f};
    const float gy[] = {0.0f, 0.01f, 0.02f, -0.02f, 0.01f};
    const float ax[] = {0.0f, 0.1f, 0.2f, -0.1f, 0.05f};
    const float ay[] = {0.0f, 0.05f, 0.1f, 0.0f, -0.05f};
    const float az[] = {1.0f, 0.99f, 0.98f, 1.0f, 0.97f};
    float roll_run[8];
    float pitch_run[8];

    BreezeComplementaryFilter_Init(&cf, 0.9f, 0.01f);
    pf("complementary_roll_init", cf.roll);
    pf("complementary_pitch_init", cf.pitch);
    pf("complementary_alpha_init", cf.alpha);
    pf("complementary_dt_init", cf.dt);
    for (step_i = 0; step_i < 5; step_i++) {
        /* gyro_z is passed but not used: the filter has no yaw state. */
        BreezeComplementaryFilter_Update(&cf, gx[step_i], gy[step_i], 0.5f, ax[step_i], ay[step_i], az[step_i]);
        roll_run[step_i] = BreezeComplementaryFilter_GetRoll(&cf);
        pitch_run[step_i] = BreezeComplementaryFilter_GetPitch(&cf);
    }
    pvals("complementary_run_roll", roll_run, 5);
    pvals("complementary_run_pitch", pitch_run, 5);

    /* --- Kalman ---------------------------------------------------------- */
    BreezeKalmanFilter1D kf;
    const float meas[] = {1.0f, 2.0f, 3.0f, 2.5f, 4.0f};

    BreezeKalmanFilter1D_Init(&kf, 0.01f, 0.1f, 1.0f, 0.0f);
    pf("kalman_x_init", kf.x);
    pf("kalman_p_init", kf.p);
    pf("kalman_q_init", kf.q);
    pf("kalman_r_init", kf.r);
    pf("kalman_k_init", kf.k);
    pf("kalman_a_init", kf.a);
    pf("kalman_h_init", kf.h);

    for (step_i = 0; step_i < 5; step_i++) run[step_i] = BreezeKalmanFilter1D_Update(&kf, meas[step_i]);
    pvals("kalman_run", run, 5);
    pf("kalman_x_after", BreezeKalmanFilter1D_GetState(&kf));
    pf("kalman_p_after", BreezeKalmanFilter1D_GetCovariance(&kf));
    pf("kalman_k_after", BreezeKalmanFilter1D_GetGain(&kf));

    BreezeKalmanFilter1D_Init(&kf, 0.01f, 0.1f, 1.0f, 0.0f);
    BreezeKalmanFilter1D_SetStateTransition(&kf, 0.9f);
    for (step_i = 0; step_i < 5; step_i++) run[step_i] = BreezeKalmanFilter1D_Update(&kf, meas[step_i]);
    pvals("kalman_transition_run", run, 5);
    pf("kalman_a_after_set", kf.a);

    BreezeKalmanFilter1D_Init(&kf, 0.01f, 0.1f, 1.0f, 0.0f);
    BreezeKalmanFilter1D_SetMeasurementCoefficient(&kf, 2.0f);
    for (step_i = 0; step_i < 5; step_i++) run[step_i] = BreezeKalmanFilter1D_Update(&kf, meas[step_i]);
    pvals("kalman_measurement_run", run, 5);
    pf("kalman_h_after_set", kf.h);

    /* The 4-dimensional type is declared in the header with no functions at all -
     * "waiting for the math module", which now exists. Its layout is recorded so
     * the gap is visible in the fixture; the port does not fill it (REVIEW §33). */
    printf("kalman_nd_layout %zu %zu\n", sizeof(BreezeKalmanFilterND), _Alignof(BreezeKalmanFilterND));

    /* --- median ---------------------------------------------------------- */
    float mbuf[6];
    float msorted[6];
    BreezeMedianFilter mf;
    const float min[] = {1.0f, 100.0f, 2.0f, 3.0f, 2.0f, 1.5f, 2.2f};

    BreezeMedianFilter_Init(&mf, mbuf, msorted, 5);
    for (step_i = 0; step_i < 7; step_i++) run[step_i] = BreezeMedianFilter_Update(&mf, min[step_i]);
    pvals("median_run", run, 7);

    BreezeMedianFilter_Reset(&mf);
    pf("median_reset_then_update", BreezeMedianFilter_Update(&mf, 9.0f));

    /* An even window averages the two middle values. */
    float ebuf[6];
    float esorted[6];
    BreezeMedianFilter_Init(&mf, ebuf, esorted, 4);
    for (step_i = 0; step_i < 6; step_i++) run[step_i] = BreezeMedianFilter_Update(&mf, min[step_i]);
    pvals("median_even_window_run", run, 6);

    /* The insertion sort is part of the header's API, so it is checked directly. */
    float tosort[6] = {3.0f, 1.0f, 4.0f, 1.5f, 5.0f, 2.0f};
    BreezeMedianFilter_InsertionSort(tosort, 6);
    pvals("median_insertion_sort", tosort, 6);

    /* Never initialised: the C version passes the input straight through. */
    BreezeMedianFilter mf_fresh = {NULL, NULL, 0, 0, 0};
    pf("median_update_without_init", BreezeMedianFilter_Update(&mf_fresh, 3.5f));

    /* Image median over a 4x3 image with an impulse in the middle. The impulse is
     * what a median filter is for, so it should be gone from the output. */
    unsigned char src_img[12] = {10, 20, 30, 40,
                                 50, 200, 60, 70,
                                 80, 90, 100, 110};
    unsigned char dst_img[12];
    memset(dst_img, 0, sizeof dst_img);
    BreezeMedianFilterImage(src_img, dst_img, 4, 3, 3, 0);
    pbytes("median_image_3x3", dst_img, 12);

    /* An even kernel size is bumped up to the next odd one. */
    memset(dst_img, 0, sizeof dst_img);
    BreezeMedianFilterImage(src_img, dst_img, 4, 3, 4, 0);
    pbytes("median_image_even_kernel", dst_img, 12);

    /* A stride wider than the image: the padding columns are addressable but
     * never written, so whatever was there stays. Pre-filling with 0xEE shows
     * exactly which bytes the function owns. */
    unsigned char src_str[15] = {1, 2, 3, 99, 99,
                                 4, 5, 6, 99, 99,
                                 7, 8, 9, 99, 99};
    unsigned char dst_str[15];
    memset(dst_str, 0xEE, sizeof dst_str);
    BreezeMedianFilterImage(src_str, dst_str, 3, 3, 3, 5);
    pbytes("median_image_stride", dst_str, 15);

    return 0;
}
