/**
 * @file gen_math_corpus.c
 * @brief Prints what the C math library answers, so the Zig port can be checked
 *        against the implementation it replaces.
 *
 * ARCHITECTURE.md §8 says each migrated module is checked against the C version.
 * "Checked against" needs a definition, and the honest one is: the C code runs,
 * and its answers are committed as data that the Zig tests compare with. This
 * program produces that data.
 *
 *   gcc -std=gnu17 -Wall -Wextra -Werror tools/corpus/gen_math_corpus.c -o gen -lm
 *   ./gen > src/math/testdata/math_corpus.txt
 *
 * The output is deliberately flat text instead of a Zig literal: the fixture can
 * then be regenerated by anyone with a C compiler, without a Zig build, and a
 * diff of it is readable in review. `tools/check-c.ps1` regenerates it and fails
 * if the committed copy no longer matches, so an oracle that drifts is a red
 * build rather than a test that quietly compares against the wrong numbers.
 *
 * Values are printed with %.9g, which round-trips every `float` exactly: the
 * fixture loses nothing, so a mismatch is a real difference and not a printing
 * artefact.
 *
 * Cases are added module by module as the migration proceeds; vector, matrix,
 * quaternion and interpolation are covered, and the filters are being added.
 *
 * Stateful things (the filters) get one case per *run*: the values are the
 * outputs in order, so a scenario is one line rather than one line per step.
 */

#include <math.h>
#include <stddef.h>
#include <stdio.h>
#include <string.h>

#include "../../include/breeze/control/adaptive_controller.h"
#include "../../include/breeze/control/fuzzy_controller.h"
#include "../../include/breeze/control/platform/balance_controller.h"
#include "../../include/breeze/control/platform/ackermann_steering.h"
#include "../../include/breeze/control/platform/differential_drive.h"
#include "../../include/breeze/control/platform/mecanum_drive.h"
#include "../../include/breeze/control/platform/omni_drive.h"
#include "../../include/breeze/control/pid_controller.h"
#include "../../include/breeze/control/state_feedback_controller.h"
#include "../../include/breeze/filter/complementary_filter.h"
#include "../../include/breeze/filter/high_pass_filter.h"
#include "../../include/breeze/filter/kalman_filter.h"
#include "../../include/breeze/filter/low_pass_filter.h"
#include "../../include/breeze/filter/median_filter.h"
#include "../../include/breeze/math/interpolation.h"
#include "../../include/breeze/math/matrix.h"
#include "../../include/breeze/math/quaternion.h"
#include "../../include/breeze/math/vector.h"

/* One printer per arity keeps `main` a readable list of cases. */
static void p2(const char* name, BreezeVector2D v) {
    printf("%s %.9g %.9g\n", name, (double)v.x, (double)v.y);
}

static void p3(const char* name, BreezeVector3D v) {
    printf("%s %.9g %.9g %.9g\n", name, (double)v.x, (double)v.y, (double)v.z);
}

static void p4(const char* name, BreezeVector4D v) {
    printf("%s %.9g %.9g %.9g %.9g\n", name,
           (double)v.x, (double)v.y, (double)v.z, (double)v.w);
}

static void pf(const char* name, float v) {
    printf("%s %.9g\n", name, (double)v);
}

static void pi(const char* name, int v) {
    printf("%s %d\n", name, v);
}

static void pq(const char* name, const BreezeQuaternion* q) {
    printf("%s %.9g %.9g %.9g %.9g\n", name,
           (double)q->w, (double)q->x, (double)q->y, (double)q->z);
}

static void p3f(const char* name, float a, float b, float c) {
    printf("%s %.9g %.9g %.9g\n", name, (double)a, (double)b, (double)c);
}

/* A run of coefficients. The C spline never writes a[n-1], b[n-1] or d[n-1] -
 * `Evaluate` cannot reach them - so only the initialised range is printed here,
 * and the port's arrays are sized to exactly that range. */
static void pvals(const char* name, const float* values, int n) {
    int i;
    printf("%s", name);
    for (i = 0; i < n; i++) printf(" %.9g", (double)values[i]);
    putchar('\n');
}

static void pbp(const char* name, const BreezeBezierPoint* p) {
    printf("%s %.9g %.9g\n", name, (double)p->x, (double)p->y);
}

/* Image buffers: bytes, printed as integers. They parse as floats on the Zig
 * side, which is all the comparison needs - and printing them as integers keeps
 * a byte buffer readable in the fixture. */
static void pbytes(const char* name, const unsigned char* bytes, int n) {
    int i;
    printf("%s", name);
    for (i = 0; i < n; i++) printf(" %d", (int)bytes[i]);
    putchar('\n');
}

/* --- a fake mobile platform, for the differential drive cases --------------- */
/* The C controllers reach the hardware through function pointers, so recording
 * what they command means supplying our own. These live here rather than in the
 * case list so the cases read as a scenario. */

/* Four slots, because the omni and mecanum platforms have up to four wheels. */
static float g_motor_speed[4];
static int g_motor_id[4];
static int g_motor_calls;
static int g_encoder_step;
static int g_encoder_reset;

static void fake_set_motor(int motor_id, float speed) {
    if (g_motor_calls < 4) {
        g_motor_id[g_motor_calls] = motor_id;
        g_motor_speed[g_motor_calls] = speed;
    }
    g_motor_calls++;
}

/* One scripted sequence per encoder id, indexed by the *pass* - which the case
 * sets before each Update. Advancing a counter inside here would depend on how
 * many wheels a platform reads, and the wheel counts differ. */
/* IMU scripts for the balance controller: mild by default, tilting or failing on
 * request. The pass index selects the sample, as for the encoders. */
static int g_imu_fail;
static int g_imu_tilt;

static int fake_get_imu(BreezeIMUData* out) {
    if (g_imu_fail) return 0;

    if (g_imu_tilt) {
        out->gyro_x = 0.0f;
        out->gyro_y = 10.0f;
        out->gyro_z = 0.0f;
        out->accel_x = -1.0f;
        out->accel_y = 0.0f;
        out->accel_z = 1.0f;
        return 1;
    }

    static const float gy[] = {0.0f, 0.05f, -0.05f, 0.1f, -0.1f};
    static const float axs[] = {0.0f, 0.05f, -0.05f, 0.1f, -0.1f};
    int i = g_encoder_step % 5;

    out->gyro_x = 0.0f;
    out->gyro_y = gy[i];
    out->gyro_z = 0.0f;
    out->accel_x = axs[i];
    out->accel_y = 0.0f;
    out->accel_z = 1.0f;
    return 1;
}

static float fake_get_encoder(int encoder_id, int reset) {
    /* Counts chosen so the wheel speeds land near the target: one count is
     * 2*pi*r/resolution/dt = 0.01885 m/s, so ~26 counts is ~0.5 m/s. Values that
     * saturate the PID would only exercise the clamp. */
    static const float seq[4][3] = {
        {25.0f, 28.0f, 24.0f},
        {27.0f, 26.0f, 30.0f},
        {26.0f, 25.0f, 29.0f},
        {28.0f, 27.0f, 25.0f},
    };
    g_encoder_reset = reset;   /* recorded, because nothing else would check it */

    int idx = (encoder_id >= 1 && encoder_id <= 4) ? encoder_id - 1 : 0;
    return seq[idx][g_encoder_step % 3];
}

/* A matrix prints its *used* region row-major, and the shape lives in the case
 * name (`matrix_add_2x2`) rather than in the data. The Zig type carries its
 * shape at compile time, so printing rows and cols as values would be comparing
 * a compile-time fact against itself; what needs checking is the arithmetic. */
static void pm(const char* name, const BreezeMatrix* m) {
    int i, j;
    printf("%s", name);
    for (i = 0; i < m->rows; i++) {
        for (j = 0; j < m->cols; j++) printf(" %.9g", (double)m->data[i][j]);
    }
    putchar('\n');
}

/* Row-major fill, so each case reads as the matrix it is about. */
static void setm(BreezeMatrix* m, int rows, int cols, const float* values) {
    int i, j, k = 0;
    BreezeMatrix_Init(m, rows, cols);
    for (i = 0; i < rows; i++) {
        for (j = 0; j < cols; j++) m->data[i][j] = values[k++];
    }
}

int main(void) {
    /* The header, not documentation: a reader of the fixture should be able to
     * tell where it came from without opening this file. */
    printf("# Breeze math corpus - answers produced by the C library in include/breeze/.\n");
    printf("# Generated by tools/corpus/gen_math_corpus.c; do not edit by hand.\n");
    printf("# %s\n", "format: <case> <value>...  (floats printed with %.9g, which round-trips float)");

    const BreezeVector2D a2 = {1.0f, 2.0f};
    const BreezeVector2D b2 = {3.0f, -4.0f};
    const BreezeVector3D a3 = {1.0f, 2.0f, 3.0f};
    const BreezeVector3D b3 = {-4.0f, 5.0f, 6.0f};
    const BreezeVector4D a4 = {1.0f, 2.0f, 3.0f, 4.0f};
    const BreezeVector4D b4 = {5.0f, -6.0f, 7.0f, 8.0f};
    BreezeVector2D r2;
    BreezeVector3D r3;
    BreezeVector4D r4;

    /* Layout. The Zig types are plain structs with the same fields, so pinning
     * size and alignment here is what makes "the two representations are
     * interchangeable in memory" a checked claim rather than a hope. */
    printf("vec2_layout %zu %zu\n", sizeof(BreezeVector2D), _Alignof(BreezeVector2D));
    printf("vec3_layout %zu %zu\n", sizeof(BreezeVector3D), _Alignof(BreezeVector3D));
    printf("vec4_layout %zu %zu\n", sizeof(BreezeVector4D), _Alignof(BreezeVector4D));
    pi("vec2_offset_x", (int)offsetof(BreezeVector2D, x));
    pi("vec2_offset_y", (int)offsetof(BreezeVector2D, y));
    pi("vec3_offset_z", (int)offsetof(BreezeVector3D, z));
    pi("vec4_offset_w", (int)offsetof(BreezeVector4D, w));

    /* --- 2D ------------------------------------------------------------- */
    BreezeVector2D_Init(&r2, 1.5f, -2.5f);
    p2("vec2_init", r2);

    BreezeVector2D_Add(&r2, &a2, &b2);
    p2("vec2_add", r2);

    BreezeVector2D_Subtract(&r2, &a2, &b2);
    p2("vec2_subtract", r2);

    BreezeVector2D_ScalarMultiply(&r2, &a2, -3.0f);
    p2("vec2_scalar_multiply", r2);

    pf("vec2_dot", BreezeVector2D_DotProduct(&a2, &b2));
    pf("vec2_length", BreezeVector2D_Length(&b2));

    pi("vec2_normalize_ok", BreezeVector2D_Normalize(&r2, &b2));
    p2("vec2_normalize", r2);

    /* The degenerate case: the C version refuses and leaves the out parameter
     * alone. The port has to refuse too, and say so in the type. */
    r2 = (BreezeVector2D){99.0f, 99.0f};
    pi("vec2_normalize_zero_ok", BreezeVector2D_Normalize(&r2, &(const BreezeVector2D){0.0f, 0.0f}));
    p2("vec2_normalize_zero_untouched", r2);

    /* Normalizing a vector already of length 1 must be a no-op. */
    BreezeVector2D_Normalize(&r2, &b2);
    {
        BreezeVector2D again;
        pi("vec2_normalize_twice_ok", BreezeVector2D_Normalize(&again, &r2));
        p2("vec2_normalize_twice", again);
    }

    /* --- 3D ------------------------------------------------------------- */
    BreezeVector3D_Init(&r3, 1.5f, -2.5f, 3.25f);
    p3("vec3_init", r3);

    BreezeVector3D_Add(&r3, &a3, &b3);
    p3("vec3_add", r3);

    BreezeVector3D_Subtract(&r3, &a3, &b3);
    p3("vec3_subtract", r3);

    BreezeVector3D_ScalarMultiply(&r3, &a3, 0.5f);
    p3("vec3_scalar_multiply", r3);

    pf("vec3_dot", BreezeVector3D_DotProduct(&a3, &b3));
    pf("vec3_length", BreezeVector3D_Length(&b3));

    BreezeVector3D_CrossProduct(&r3, &a3, &b3);
    p3("vec3_cross", r3);

    /* The C version documents a temporary precisely so that in-place use is
     * safe. Both spellings are captured, because the port must keep both. */
    r3 = a3;
    BreezeVector3D_CrossProduct(&r3, &r3, &b3);
    p3("vec3_cross_in_place_a", r3);

    r3 = b3;
    BreezeVector3D_CrossProduct(&r3, &a3, &r3);
    p3("vec3_cross_in_place_b", r3);

    /* Cross product of parallel vectors is exactly zero. */
    BreezeVector3D_CrossProduct(&r3, &a3, &a3);
    p3("vec3_cross_self", r3);

    pi("vec3_normalize_ok", BreezeVector3D_Normalize(&r3, &b3));
    p3("vec3_normalize", r3);

    r3 = (BreezeVector3D){99.0f, 99.0f, 99.0f};
    pi("vec3_normalize_zero_ok", BreezeVector3D_Normalize(&r3, &(const BreezeVector3D){0.0f, 0.0f, 0.0f}));
    p3("vec3_normalize_zero_untouched", r3);

    /* Just under and just over the 1e-6 threshold the C code uses. This is the
     * boundary the port must copy rather than "improve": it is a contract the
     * callers already rely on. */
    pi("vec3_normalize_tiny_ok", BreezeVector3D_Normalize(&r3, &(const BreezeVector3D){1.0e-7f, 0.0f, 0.0f}));
    pi("vec3_normalize_just_above_ok", BreezeVector3D_Normalize(&r3, &(const BreezeVector3D){1.0e-3f, 0.0f, 0.0f}));

    /* --- 4D ------------------------------------------------------------- */
    BreezeVector4D_Init(&r4, 1.0f, 2.0f, 3.0f, 4.0f);
    p4("vec4_init", r4);

    BreezeVector4D_Add(&r4, &a4, &b4);
    p4("vec4_add", r4);

    BreezeVector4D_Subtract(&r4, &a4, &b4);
    p4("vec4_subtract", r4);

    BreezeVector4D_ScalarMultiply(&r4, &a4, 2.5f);
    p4("vec4_scalar_multiply", r4);

    pf("vec4_dot", BreezeVector4D_DotProduct(&a4, &b4));
    pf("vec4_length", BreezeVector4D_Length(&b4));

    pi("vec4_normalize_ok", BreezeVector4D_Normalize(&r4, &b4));
    p4("vec4_normalize", r4);

    /* --- matrix ---------------------------------------------------------- */
    BreezeMatrix ma, mr;

    /* Determinant 1, and its inverse is the textbook integer matrix
     * [[-24,18,5],[20,-15,-4],[-5,4,1]] - exact in float, so a mismatch here is
     * the port's fault and not rounding. */
    const float b3v[] = {1.0f, 2.0f, 3.0f, 0.0f, 1.0f, 4.0f, 5.0f, 6.0f, 0.0f};
    BreezeMatrix b3m, four4;
    setm(&b3m, 3, 3, b3v);
    setm(&four4, 4, 4, (const float[]){1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f,
                                       0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f});

    printf("matrix_layout %zu %zu\n", sizeof ma, _Alignof(BreezeMatrix));
    printf("matrix_data_bytes %zu\n", sizeof ma.data);

    /* Init zeroes only the used region - the storage beyond it is left alone,
     * which is a property the Zig type cannot have because it has no storage
     * beyond its shape. Captured here so the difference is on the record. */
    BreezeMatrix_Init(&ma, 2, 3);
    pm("matrix_init_2x3", &ma);

    BreezeMatrix_Init(&ma, 3, 3);
    BreezeMatrix_SetIdentity(&ma);
    pm("matrix_identity_3x3", &ma);

    /* Non-square identity: the C code fills ones only out to min(rows, cols). */
    BreezeMatrix_Init(&ma, 2, 3);
    BreezeMatrix_SetIdentity(&ma);
    pm("matrix_identity_2x3", &ma);

    BreezeMatrix_Init(&ma, 2, 2);
    BreezeMatrix_SetElement(&ma, 0, 1, 7.5f);
    pf("matrix_get_element", BreezeMatrix_GetElement(&ma, 0, 1));
    pf("matrix_get_out_of_range", BreezeMatrix_GetElement(&ma, 5, 0));
    pm("matrix_set_get_2x2", &ma);
    BreezeMatrix_SetElement(&ma, 9, 9, 1.0f); /* silently ignored */
    pm("matrix_set_out_of_range_2x2", &ma);

    const float a2v[] = {4.0f, 7.0f, 2.0f, 6.0f};
    const float b2v[] = {1.0f, 2.0f, 3.0f, 4.0f};
    const float singv[] = {1.0f, 2.0f, 2.0f, 4.0f};
    BreezeMatrix ma2, mb2, msing;
    setm(&ma2, 2, 2, a2v);
    setm(&mb2, 2, 2, b2v);
    setm(&msing, 2, 2, singv);

    pi("matrix_add_2x2_ok", BreezeMatrix_Add(&mr, &ma2, &mb2));
    pm("matrix_add_2x2", &mr);

    pi("matrix_subtract_2x2_ok", BreezeMatrix_Subtract(&mr, &ma2, &mb2));
    pm("matrix_subtract_2x2", &mr);

    pi("matrix_multiply_2x2_ok", BreezeMatrix_Multiply(&mr, &ma2, &mb2));
    pm("matrix_multiply_2x2", &mr);

    /* In place, which the C version supports on purpose (it multiplies into a
     * temporary precisely so that result may alias an input). */
    setm(&mr, 2, 2, a2v);
    pi("matrix_multiply_in_place_ok", BreezeMatrix_Multiply(&mr, &mr, &mb2));
    pm("matrix_multiply_in_place_2x2", &mr);

    const float pv[] = {1.0f, 2.0f, 3.0f, 4.0f, 5.0f, 6.0f};    /* 2x3 */
    const float qv[] = {7.0f, 8.0f, 9.0f, 10.0f, 11.0f, 12.0f};  /* 3x2 */
    BreezeMatrix p, q, r;
    setm(&p, 2, 3, pv);
    setm(&q, 3, 2, qv);

    pi("matrix_multiply_2x3_3x2_ok", BreezeMatrix_Multiply(&r, &p, &q));
    pm("matrix_multiply_2x3_3x2", &r);

    /* Inner dimensions disagree: the C version refuses and says so in its
     * return value. The Zig signature makes this unrepresentable. */
    setm(&r, 2, 2, b2v);
    pi("matrix_multiply_mismatch_ok", BreezeMatrix_Multiply(&r, &ma2, &q));

    const float sv[] = {2.0f, -1.0f, 0.5f, 3.0f, 4.0f, -2.0f}; /* 3x2 */
    BreezeMatrix s;
    setm(&s, 3, 2, sv);
    BreezeMatrix_ScalarMultiply(&r, &s, -1.5f);
    pm("matrix_scalar_multiply_3x2", &r);

    BreezeMatrix_Transpose(&r, &p);
    pm("matrix_transpose_2x3", &r);

    /* In place again: transpose is where aliasing is easiest to get wrong. */
    setm(&r, 3, 3, (const float[]){1.0f, 2.0f, 3.0f, 4.0f, 5.0f, 6.0f, 7.0f, 8.0f, 9.0f});
    BreezeMatrix_Transpose(&r, &r);
    pm("matrix_transpose_in_place_3x3", &r);

    pf("matrix_det_2x2", BreezeMatrix_Determinant2x2(&ma2));
    pf("matrix_det_3x3", BreezeMatrix_Determinant3x3(&b3m));
    pf("matrix_det_dispatch_2x2", BreezeMatrix_Determinant(&ma2));
    pf("matrix_det_dispatch_3x3", BreezeMatrix_Determinant(&b3m));
    /* Not square: refused. */
    pf("matrix_det_nonsquare", BreezeMatrix_Determinant(&p));
    /* Square but unsupported: the C code returns 0 rather than computing it.
     * The port makes this a compile error instead, so no Zig case reads this. */
    pf("matrix_det_4x4", BreezeMatrix_Determinant(&four4));

    pi("matrix_inverse_2x2_ok", BreezeMatrix_Inverse2x2(&mr, &ma2));
    pm("matrix_inverse_2x2", &mr);

    pi("matrix_inverse_3x3_ok", BreezeMatrix_Inverse3x3(&mr, &b3m));
    pm("matrix_inverse_3x3", &mr);

    pi("matrix_inverse_dispatch_2x2_ok", BreezeMatrix_Inverse(&mr, &ma2));
    pm("matrix_inverse_dispatch_2x2", &mr);

    pi("matrix_inverse_4x4_ok", BreezeMatrix_Inverse(&mr, &four4));

    /* Singular: refused, and - because the refusal happens before the write -
     * the caller's result is untouched. The Zig port returns an error instead,
     * so what is checked there is the error, not the untouched buffer. */
    setm(&mr, 2, 2, b2v);
    pi("matrix_inverse_singular_ok", BreezeMatrix_Inverse2x2(&mr, &msing));
    pm("matrix_inverse_singular_untouched", &mr);

    /* --- quaternion ------------------------------------------------------ */
    BreezeQuaternion qa, qb, qr;
    float qr_roll, qr_pitch, qr_yaw;

    printf("quat_layout %zu %zu\n", sizeof qa, _Alignof(BreezeQuaternion));

    BreezeQuaternion_SetIdentity(&qa);
    pq("quat_identity", &qa);

    BreezeQuaternion_Init(&qa, 1.5f, -2.5f, 3.25f, -4.75f);
    pq("quat_init", &qa);

    /* Trigonometry enters here, so these are the cases where a libm difference
     * between the two implementations could show up as a last-bit disagreement.
     * The comparison tolerance exists for them. */
    BreezeQuaternion_FromEulerZYX(&qa, 0.3f, -0.4f, 1.1f);
    pq("quat_from_euler_zyx", &qa);

    BreezeQuaternion_FromEulerZYX(&qa, 0.0f, 0.0f, 0.0f);
    pq("quat_from_euler_zyx_zero", &qa);

    BreezeQuaternion_FromEulerZYX(&qa, 0.3f, -0.4f, 1.1f);
    BreezeQuaternion_ToEulerZYX(&qa, &qr_roll, &qr_pitch, &qr_yaw);
    p3f("quat_euler_roundtrip", qr_roll, qr_pitch, qr_yaw);

    /* pitch = +pi/2 is the gimbal-lock branch, where the C code sets roll to 0
     * by convention and takes yaw from a different formula. */
    BreezeQuaternion_FromEulerZYX(&qa, 0.3f, (float)(M_PI / 2.0), 1.1f);
    pq("quat_from_euler_zyx_gimbal", &qa);
    BreezeQuaternion_ToEulerZYX(&qa, &qr_roll, &qr_pitch, &qr_yaw);
    p3f("quat_euler_gimbal", qr_roll, qr_pitch, qr_yaw);

    const BreezeVector3D axis_xyz = {1.0f, 2.0f, 2.0f};
    BreezeQuaternion_FromAxisAngle(&qa, &axis_xyz, 0.7f);
    pq("quat_from_axis_angle", &qa);

    /* A degenerate axis: the C version falls back to the identity rather than
     * failing, because "rotate by any angle about no axis" has an answer. */
    BreezeQuaternion_FromAxisAngle(&qa, &(const BreezeVector3D){0.0f, 0.0f, 0.0f}, 0.7f);
    pq("quat_from_axis_angle_degenerate", &qa);

    const BreezeVector3D axis_x = {1.0f, 0.0f, 0.0f};
    BreezeQuaternion_FromAxisAngle(&qa, &axis_x, (float)(M_PI / 3.0));
    pq("quat_from_axis_angle_x", &qa);

    BreezeQuaternion_Init(&qa, 1.5f, -2.5f, 3.25f, -4.75f);
    pf("quat_magnitude", BreezeQuaternion_Magnitude(&qa));

    pi("quat_normalize_ok", BreezeQuaternion_Normalize(&qr, &qa));
    pq("quat_normalize", &qr);

    /* Note the threshold asymmetry, which the port has to keep: Normalize
     * compares the *magnitude* against 1e-6 while Inverse compares the squared
     * magnitude against the same number. A quaternion of magnitude 1e-4 is
     * therefore accepted by one and refused by the other. */
    pq("quat_normalize_degenerate_untouched", &(const BreezeQuaternion){9.0f, 9.0f, 9.0f, 9.0f});
    pi("quat_normalize_degenerate_ok", BreezeQuaternion_Normalize(&(BreezeQuaternion){9.0f, 9.0f, 9.0f, 9.0f}, &(const BreezeQuaternion){1.0e-7f, 0.0f, 0.0f, 0.0f}));
    pi("quat_inverse_degenerate_ok", BreezeQuaternion_Inverse(&(BreezeQuaternion){9.0f, 9.0f, 9.0f, 9.0f}, &(const BreezeQuaternion){1.0e-7f, 0.0f, 0.0f, 0.0f}));
    /* Magnitude 1e-4: Normalize accepts (1e-4 >= 1e-6), Inverse refuses
     * (1e-8 < 1e-6). Both statuses are captured so the asymmetry is pinned. */
    pi("quat_normalize_boundary_ok", BreezeQuaternion_Normalize(&(BreezeQuaternion){9.0f, 9.0f, 9.0f, 9.0f}, &(const BreezeQuaternion){1.0e-4f, 0.0f, 0.0f, 0.0f}));
    pi("quat_inverse_boundary_ok", BreezeQuaternion_Inverse(&(BreezeQuaternion){9.0f, 9.0f, 9.0f, 9.0f}, &(const BreezeQuaternion){1.0e-4f, 0.0f, 0.0f, 0.0f}));

    BreezeQuaternion_Init(&qa, 1.5f, -2.5f, 3.25f, -4.75f);
    BreezeQuaternion_Conjugate(&qr, &qa);
    pq("quat_conjugate", &qr);

    pi("quat_inverse_ok", BreezeQuaternion_Inverse(&qr, &qa));
    pq("quat_inverse", &qr);

    /* 90 degrees about z, then 90 degrees about x: two unit quaternions whose
     * product is another one, and whose components are exactly representable
     * halves of a square root - no special values, no gimbal lock. */
    const BreezeVector3D axis_z = {0.0f, 0.0f, 1.0f};
    BreezeQuaternion_FromAxisAngle(&qa, &axis_z, (float)(M_PI / 2.0));
    BreezeQuaternion_FromAxisAngle(&qb, &axis_x, (float)(M_PI / 2.0));
    pq("quat_z90", &qa);
    pq("quat_x90", &qb);

    BreezeQuaternion_Multiply(&qr, &qa, &qb);
    pq("quat_multiply", &qr);

    /* The in-place spelling the C version supports by multiplying into a
     * temporary. */
    BreezeQuaternion q_in_place = qa;
    BreezeQuaternion_Multiply(&q_in_place, &q_in_place, &qb);
    pq("quat_multiply_in_place", &q_in_place);

    const BreezeVector3D vx = {1.0f, 0.0f, 0.0f};
    BreezeVector3D vr;
    BreezeQuaternion_RotateVector(&vr, &qa, &vx);
    p3("quat_rotate", vr);

    /* Result aliasing the input vector: the C version writes only at the end,
     * so this is safe there too. */
    vr = vx;
    BreezeQuaternion_RotateVector(&vr, &qa, &vr);
    p3("quat_rotate_in_place", vr);

    BreezeQuaternion_SetIdentity(&qb);
    BreezeQuaternion_Slerp(&qr, &qb, &qa, 0.0f);
    pq("quat_slerp_t0", &qr);
    BreezeQuaternion_Slerp(&qr, &qb, &qa, 0.25f);
    pq("quat_slerp_t025", &qr);
    BreezeQuaternion_Slerp(&qr, &qb, &qa, 0.5f);
    pq("quat_slerp_t05", &qr);
    BreezeQuaternion_Slerp(&qr, &qb, &qa, 1.0f);
    pq("quat_slerp_t1", &qr);
    /* t outside [0, 1] is clamped, not extrapolated. */
    BreezeQuaternion_Slerp(&qr, &qb, &qa, 1.5f);
    pq("quat_slerp_clamped", &qr);

    /* Nearly identical inputs take the linear branch (dot > 0.9999). */
    BreezeQuaternion_Slerp(&qr, &qb, &qb, 0.5f);
    pq("quat_slerp_linear_branch", &qr);

    /* Negative dot: the C version negates b to take the short way round. */
    BreezeQuaternion_Init(&qb, -1.0f, 0.0f, 0.0f, 0.0f);
    BreezeQuaternion_Slerp(&qr, &qa, &qb, 0.5f);
    pq("quat_slerp_negative_dot", &qr);

    /* --- interpolation --------------------------------------------------- */
    /* The three scalar curves. Cosine is the one that brings cosf in; Hermite
     * takes the neighbouring points and two shape parameters. */
    pf("interp_linear", BreezeInterpolation_Linear(0.0f, 0.0f, 2.0f, 4.0f, 0.5f));
    /* x0 and x1 within 1e-6 of each other: the C code answers with the midpoint
     * rather than dividing by (almost) zero. */
    pf("interp_linear_degenerate", BreezeInterpolation_Linear(1.0f, 3.0f, 1.0f + 1.0e-7f, 7.0f, 5.0f));

    pf("interp_cosine_mu0", BreezeInterpolation_Cosine(0.0f, 10.0f, 0.0f));
    pf("interp_cosine_mu025", BreezeInterpolation_Cosine(0.0f, 10.0f, 0.25f));
    pf("interp_cosine_mu05", BreezeInterpolation_Cosine(0.0f, 10.0f, 0.5f));
    pf("interp_cosine_mu1", BreezeInterpolation_Cosine(0.0f, 10.0f, 1.0f));

    pf("interp_hermite", BreezeInterpolation_CubicHermite(0.0f, 1.0f, 2.0f, 3.0f, 0.5f, 0.0f, 0.0f));
    pf("interp_hermite_tension_bias", BreezeInterpolation_CubicHermite(0.0f, 1.0f, 2.0f, 3.0f, 0.5f, 0.3f, 0.2f));

    float spx[] = {0.0f, 1.0f, 2.0f, 3.0f, 4.0f};
    float spy[] = {0.0f, 1.0f, 0.0f, 1.0f, 0.0f};
    BreezeSplineInterpolation sp;

    pi("spline_init_ok", BreezeSplineInterpolation_Init(&sp, spx, spy, 5, 0));
    pvals("spline_a", sp.a, 4);
    pvals("spline_b", sp.b, 4);
    pvals("spline_c", sp.c, 5);
    pvals("spline_d", sp.d, 4);

    /* Evaluate clamps outside the knot range and lands exactly on y at a knot. */
    pf("spline_eval_below_range", BreezeSplineInterpolation_Evaluate(&sp, -1.0f));
    pf("spline_eval_at_knot0", BreezeSplineInterpolation_Evaluate(&sp, 0.0f));
    pf("spline_eval_at_knot2", BreezeSplineInterpolation_Evaluate(&sp, 2.0f));
    pf("spline_eval_between", BreezeSplineInterpolation_Evaluate(&sp, 1.5f));
    pf("spline_eval_above_range", BreezeSplineInterpolation_Evaluate(&sp, 9.0f));
    BreezeSplineInterpolation_Free(&sp);

    /* Collinear knots: a natural cubic spline through them is that line exactly,
     * so this case doubles as a check that is independent of the oracle. */
    float linx[] = {0.0f, 1.0f, 2.0f, 3.0f};
    float liny[] = {1.0f, 3.0f, 5.0f, 7.0f};
    pi("spline_init_linear_ok", BreezeSplineInterpolation_Init(&sp, linx, liny, 4, 0));
    pf("spline_linear_at_0p5", BreezeSplineInterpolation_Evaluate(&sp, 0.5f));
    pf("spline_linear_at_2p5", BreezeSplineInterpolation_Evaluate(&sp, 2.5f));
    BreezeSplineInterpolation_Free(&sp);

    /* Knots that do not strictly increase: refused, and the C reason is a
     * division that would be by (almost) zero. */
    float badx[] = {0.0f, 1.0f, 1.0f, 3.0f};
    float bady[] = {0.0f, 1.0f, 2.0f, 3.0f};
    pi("spline_init_not_increasing_ok", BreezeSplineInterpolation_Init(&sp, badx, bady, 4, 0));

    pi("spline_init_too_few_ok", BreezeSplineInterpolation_Init(&sp, spx, spy, 1, 0));

    /* Bezier: pure polynomial evaluation, no solver. */
    BreezeBezierPoint bp0 = {0.0f, 0.0f};
    BreezeBezierPoint bp1 = {1.0f, 3.0f};
    BreezeBezierPoint bp2 = {4.0f, 3.0f};
    BreezeBezierPoint bp3 = {5.0f, 0.0f};
    BreezeBezierPoint bp;

    printf("bezier_layout %zu %zu\n", sizeof bp0, _Alignof(BreezeBezierPoint));

    BreezeBezierCurve_Quadratic(&bp0, &bp1, &bp2, 0.5f, &bp);
    pbp("bezier_quadratic_t05", &bp);
    BreezeBezierCurve_Quadratic(&bp0, &bp1, &bp2, 0.0f, &bp);
    pbp("bezier_quadratic_t0", &bp);

    BreezeBezierCurve_Cubic(&bp0, &bp1, &bp2, &bp3, 0.25f, &bp);
    pbp("bezier_cubic_t025", &bp);
    BreezeBezierCurve_Cubic(&bp0, &bp1, &bp2, &bp3, 0.5f, &bp);
    pbp("bezier_cubic_t05", &bp);
    BreezeBezierCurve_Cubic(&bp0, &bp1, &bp2, &bp3, 1.0f, &bp);
    pbp("bezier_cubic_t1", &bp);

    /* --- filters: the three recursive scalar ones ------------------------ */
    /* Each `*_run` case is one scenario: the inputs are fixed here, and the
     * values are the outputs in the order they came out. */
    const float steps[] = {12.0f, 13.0f, 11.0f, 18.0f, 6.0f};
    float run[8];
    int step_i;

    BreezeLowPassFilter lp;
    BreezeEWMAFilter ew;
    BreezeHighPassFilter hp;
    BreezeDCBlocker dcb;
    BreezeComplementaryFilter cf;

    BreezeLowPassFilter_Init(&lp, 0.25f, 10.0f);
    pf("lowpass_alpha_init", lp.alpha);
    pf("lowpass_prev_output_init", lp.prev_output);
    for (step_i = 0; step_i < 5; step_i++) run[step_i] = BreezeLowPassFilter_Update(&lp, steps[step_i]);
    pvals("lowpass_run", run, 5);

    /* alpha is clamped on the way in, in every entry point that takes one. */
    BreezeLowPassFilter_Init(&lp, -1.0f, 0.0f);
    pf("lowpass_alpha_clamped_low", lp.alpha);
    BreezeLowPassFilter_Init(&lp, 2.0f, 0.0f);
    pf("lowpass_alpha_clamped_high", lp.alpha);

    /* Note the direction of this formula: sample time over the sum. The high
     * pass version below divides the other way round. */
    BreezeLowPassFilter_InitWithTimeConstant(&lp, 0.5f, 0.1f, 0.0f);
    pf("lowpass_alpha_time_constant", lp.alpha);

    BreezeLowPassFilter_Init(&lp, 0.25f, 0.0f);
    BreezeLowPassFilter_SetAlpha(&lp, 0.5f);
    pf("lowpass_alpha_set", lp.alpha);
    BreezeLowPassFilter_SetTimeConstant(&lp, 0.5f, 0.5f);
    pf("lowpass_alpha_set_time_constant", lp.alpha);

    /* An invalid time constant is a silent no-op in C: nothing about the filter
     * changes, including its previous output. Captured so the port'step_i decision to
     * report an error instead is a documented difference and not a guess. */
    BreezeLowPassFilter_Init(&lp, 0.25f, 10.0f);
    BreezeLowPassFilter_InitWithTimeConstant(&lp, -1.0f, 0.1f, 99.0f);
    pf("lowpass_alpha_invalid_tc_unchanged", lp.alpha);
    pf("lowpass_prev_output_invalid_tc_unchanged", lp.prev_output);
    BreezeLowPassFilter_SetTimeConstant(&lp, 0.0f, 0.1f);
    pf("lowpass_alpha_invalid_set_tc_unchanged", lp.alpha);

    /* A zero-initialised filter has never been initialised, and the first update
     * passes its input straight through. */
    BreezeLowPassFilter lp_fresh = {0.0f, 0.0f, 0};
    pf("lowpass_first_update_uninitialised", BreezeLowPassFilter_Update(&lp_fresh, 7.5f));
    BreezeEWMAFilter ew_fresh = {0.0f, 0.0f, 0};
    pf("ewma_first_update_uninitialised", BreezeEWMAFilter_Update(&ew_fresh, 7.5f));

    BreezeLowPassFilter_Init(&lp, 0.5f, 0.0f);
    BreezeLowPassFilter_Reset(&lp, 4.0f);
    pf("lowpass_reset_then_update", BreezeLowPassFilter_Update(&lp, 8.0f));

    BreezeEWMAFilter_Init(&ew, 0.25f, 2.0f);
    pf("ewma_alpha_init", ew.alpha);
    pf("ewma_avg_init", ew.avg);
    for (step_i = 0; step_i < 5; step_i++) run[step_i] = BreezeEWMAFilter_Update(&ew, steps[step_i]);
    pvals("ewma_run", run, 5);
    BreezeEWMAFilter_Reset(&ew, 3.0f);
    pf("ewma_reset_then_update", BreezeEWMAFilter_Update(&ew, 9.0f));

    /* High pass starts uninitialised even after Init - the alpha entry points
     * deliberately leave `initialized` at zero. */
    BreezeHighPassFilter_Init(&hp, 0.25f);
    pf("highpass_alpha_init", hp.alpha);
    pf("highpass_initialised_after_init", (float)hp.initialized);
    for (step_i = 0; step_i < 5; step_i++) run[step_i] = BreezeHighPassFilter_Update(&hp, steps[step_i]);
    pvals("highpass_run", run, 5);

    BreezeHighPassFilter_InitWithTimeConstant(&hp, 0.5f, 0.1f);
    pf("highpass_alpha_time_constant", hp.alpha);

    BreezeHighPassFilter_InitWithTimeConstant(&hp, -1.0f, 0.1f);
    pf("highpass_alpha_invalid_tc_unchanged", hp.alpha);

    BreezeHighPassFilter_Init(&hp, 0.25f);
    BreezeHighPassFilter_Reset(&hp, 5.0f);
    pf("highpass_reset_then_update", BreezeHighPassFilter_Update(&hp, 5.0f));

    BreezeDCBlocker_Init(&dcb, 0.1f);
    pf("dcblock_alpha_init", dcb.alpha);
    for (step_i = 0; step_i < 5; step_i++) run[step_i] = BreezeDCBlocker_Update(&dcb, steps[step_i]);
    pvals("dcblock_run", run, 5);
    BreezeDCBlocker_Reset(&dcb, 5.0f);
    pf("dcblock_reset_then_update", BreezeDCBlocker_Update(&dcb, 5.0f));

    /* Complementary: the roll and pitch outputs of the same run. */
    const float gx[] = {0.01f, 0.02f, -0.01f, 0.03f, 0.0f};
    const float gy[] = {0.0f, 0.01f, 0.02f, -0.02f, 0.01f};
    const float ax[] = {0.0f, 0.1f, 0.2f, -0.1f, 0.05f};
    const float ay[] = {0.0f, 0.05f, 0.1f, 0.0f, -0.05f};
    const float az[] = {1.0f, 0.99f, 0.98f, 1.0f, 0.97f};
    float roll_run[8];
    float pitch_run[8];

    BreezeComplementaryFilter_Init(&cf, 0.9f, 0.01f);
    pf("complementary_roll_init", cf.roll);
    pf("complementary_pitch_init", cf.pitch);
    pf("complementary_alpha_init", cf.alpha);
    pf("complementary_dt_init", cf.dt);
    for (step_i = 0; step_i < 5; step_i++) {
        /* gyro_z is passed but not used: the filter has no yaw state. */
        BreezeComplementaryFilter_Update(&cf, gx[step_i], gy[step_i], 0.5f, ax[step_i], ay[step_i], az[step_i]);
        roll_run[step_i] = BreezeComplementaryFilter_GetRoll(&cf);
        pitch_run[step_i] = BreezeComplementaryFilter_GetPitch(&cf);
    }
    pvals("complementary_run_roll", roll_run, 5);
    pvals("complementary_run_pitch", pitch_run, 5);

    /* --- Kalman ---------------------------------------------------------- */
    BreezeKalmanFilter1D kf;
    const float meas[] = {1.0f, 2.0f, 3.0f, 2.5f, 4.0f};

    BreezeKalmanFilter1D_Init(&kf, 0.01f, 0.1f, 1.0f, 0.0f);
    pf("kalman_x_init", kf.x);
    pf("kalman_p_init", kf.p);
    pf("kalman_q_init", kf.q);
    pf("kalman_r_init", kf.r);
    pf("kalman_k_init", kf.k);
    pf("kalman_a_init", kf.a);
    pf("kalman_h_init", kf.h);

    for (step_i = 0; step_i < 5; step_i++) run[step_i] = BreezeKalmanFilter1D_Update(&kf, meas[step_i]);
    pvals("kalman_run", run, 5);
    pf("kalman_x_after", BreezeKalmanFilter1D_GetState(&kf));
    pf("kalman_p_after", BreezeKalmanFilter1D_GetCovariance(&kf));
    pf("kalman_k_after", BreezeKalmanFilter1D_GetGain(&kf));

    BreezeKalmanFilter1D_Init(&kf, 0.01f, 0.1f, 1.0f, 0.0f);
    BreezeKalmanFilter1D_SetStateTransition(&kf, 0.9f);
    for (step_i = 0; step_i < 5; step_i++) run[step_i] = BreezeKalmanFilter1D_Update(&kf, meas[step_i]);
    pvals("kalman_transition_run", run, 5);
    pf("kalman_a_after_set", kf.a);

    BreezeKalmanFilter1D_Init(&kf, 0.01f, 0.1f, 1.0f, 0.0f);
    BreezeKalmanFilter1D_SetMeasurementCoefficient(&kf, 2.0f);
    for (step_i = 0; step_i < 5; step_i++) run[step_i] = BreezeKalmanFilter1D_Update(&kf, meas[step_i]);
    pvals("kalman_measurement_run", run, 5);
    pf("kalman_h_after_set", kf.h);

    /* The 4-dimensional type is declared in the header with no functions at all -
     * "waiting for the math module", which now exists. Its layout is recorded so
     * the gap is visible in the fixture; the port does not fill it (REVIEW §33). */
    printf("kalman_nd_layout %zu %zu\n", sizeof(BreezeKalmanFilterND), _Alignof(BreezeKalmanFilterND));

    /* --- median ---------------------------------------------------------- */
    float mbuf[6];
    float msorted[6];
    BreezeMedianFilter mf;
    const float min[] = {1.0f, 100.0f, 2.0f, 3.0f, 2.0f, 1.5f, 2.2f};

    BreezeMedianFilter_Init(&mf, mbuf, msorted, 5);
    for (step_i = 0; step_i < 7; step_i++) run[step_i] = BreezeMedianFilter_Update(&mf, min[step_i]);
    pvals("median_run", run, 7);

    BreezeMedianFilter_Reset(&mf);
    pf("median_reset_then_update", BreezeMedianFilter_Update(&mf, 9.0f));

    /* An even window averages the two middle values. */
    float ebuf[6];
    float esorted[6];
    BreezeMedianFilter_Init(&mf, ebuf, esorted, 4);
    for (step_i = 0; step_i < 6; step_i++) run[step_i] = BreezeMedianFilter_Update(&mf, min[step_i]);
    pvals("median_even_window_run", run, 6);

    /* The insertion sort is part of the header's API, so it is checked directly. */
    float tosort[6] = {3.0f, 1.0f, 4.0f, 1.5f, 5.0f, 2.0f};
    BreezeMedianFilter_InsertionSort(tosort, 6);
    pvals("median_insertion_sort", tosort, 6);

    /* Never initialised: the C version passes the input straight through. */
    BreezeMedianFilter mf_fresh = {NULL, NULL, 0, 0, 0};
    pf("median_update_without_init", BreezeMedianFilter_Update(&mf_fresh, 3.5f));

    /* Image median over a 4x3 image with an impulse in the middle. The impulse is
     * what a median filter is for, so it should be gone from the output. */
    unsigned char src_img[12] = {10, 20, 30, 40,
                                 50, 200, 60, 70,
                                 80, 90, 100, 110};
    unsigned char dst_img[12];
    memset(dst_img, 0, sizeof dst_img);
    BreezeMedianFilterImage(src_img, dst_img, 4, 3, 3, 0);
    pbytes("median_image_3x3", dst_img, 12);

    /* An even kernel size is bumped up to the next odd one. */
    memset(dst_img, 0, sizeof dst_img);
    BreezeMedianFilterImage(src_img, dst_img, 4, 3, 4, 0);
    pbytes("median_image_even_kernel", dst_img, 12);

    /* A stride wider than the image: the padding columns are addressable but
     * never written, so whatever was there stays. Pre-filling with 0xEE shows
     * exactly which bytes the function owns. */
    unsigned char src_str[15] = {1, 2, 3, 99, 99,
                                 4, 5, 6, 99, 99,
                                 7, 8, 9, 99, 99};
    unsigned char dst_str[15];
    memset(dst_str, 0xEE, sizeof dst_str);
    BreezeMedianFilterImage(src_str, dst_str, 3, 3, 3, 5);
    pbytes("median_image_stride", dst_str, 15);

    /* --- PID controllers -------------------------------------------------- */
    BreezePIDController pid;
    const float pmeas[] = {0.0f, 0.5f, 1.2f, 0.9f, 1.1f, 1.0f};

    BreezePIDController_Init(&pid, BREEZE_PID_POSITION, 2.0f, 0.5f, 0.1f, 0.01f, -10.0f, 10.0f);
    BreezePIDController_SetSetpoint(&pid, 1.0f);
    for (step_i = 0; step_i < 6; step_i++) run[step_i] = BreezePIDController_Compute(&pid, pmeas[step_i]);
    pvals("pid_position_run", run, 6);
    pf("pid_position_integral_after", pid.integral);
    pf("pid_position_prev_error_after", pid.prev_error);
    pf("pid_position_prev_measurement_after", pid.prev_measurement);

    /* The incremental form keeps its own history and adds a delta to the
     * previous output. */
    BreezePIDController_Init(&pid, BREEZE_PID_INCREMENTAL, 2.0f, 0.5f, 0.1f, 0.01f, -10.0f, 10.0f);
    BreezePIDController_SetSetpoint(&pid, 1.0f);
    for (step_i = 0; step_i < 6; step_i++) run[step_i] = BreezePIDController_Compute(&pid, pmeas[step_i]);
    pvals("pid_incremental_run", run, 6);
    pf("pid_incremental_prev_output_after", pid.prev_output);
    pf("pid_incremental_prev_error_after", pid.prev_error);
    pf("pid_incremental_prev_prev_error_after", pid.prev_prev_error);

    /* The derivative filter, three ways. In the position form the two terms of
     * the "filter" are the same quantity - `(prev_error - error)/dt` is exactly
     * `(measurement - prev_measurement)/dt` for a fixed setpoint - so alpha is a
     * convex combination of a value with itself. Whether that changes any bit is
     * what these three runs are for. In the incremental form alpha is never read
     * at all. */
    BreezePIDController_Init(&pid, BREEZE_PID_POSITION, 2.0f, 0.5f, 0.1f, 0.01f, -10.0f, 10.0f);
    BreezePIDController_SetDerivativeFilter(&pid, 0.0f);
    BreezePIDController_SetSetpoint(&pid, 1.0f);
    for (step_i = 0; step_i < 6; step_i++) run[step_i] = BreezePIDController_Compute(&pid, pmeas[step_i]);
    pvals("pid_position_alpha0_run", run, 6);

    BreezePIDController_Init(&pid, BREEZE_PID_POSITION, 2.0f, 0.5f, 0.1f, 0.01f, -10.0f, 10.0f);
    BreezePIDController_SetDerivativeFilter(&pid, 0.7f);
    BreezePIDController_SetSetpoint(&pid, 1.0f);
    for (step_i = 0; step_i < 6; step_i++) run[step_i] = BreezePIDController_Compute(&pid, pmeas[step_i]);
    pvals("pid_position_alpha07_run", run, 6);

    BreezePIDController_Init(&pid, BREEZE_PID_POSITION, 2.0f, 0.5f, 0.1f, 0.01f, -10.0f, 10.0f);
    BreezePIDController_SetDerivativeFilter(&pid, 1.0f);
    BreezePIDController_SetSetpoint(&pid, 1.0f);
    for (step_i = 0; step_i < 6; step_i++) run[step_i] = BreezePIDController_Compute(&pid, pmeas[step_i]);
    pvals("pid_position_alpha1_run", run, 6);

    BreezePIDController_SetDerivativeFilter(&pid, -1.0f);
    pf("pid_alpha_clamped_low", pid.alpha);
    BreezePIDController_SetDerivativeFilter(&pid, 2.0f);
    pf("pid_alpha_clamped_high", pid.alpha);

    /* Anti-windup: the integral is clamped to its own limits, which `Init` sets
     * to the output limits unless the caller overrides them. */
    BreezePIDController_Init(&pid, BREEZE_PID_POSITION, 0.0f, 1.0f, 0.0f, 0.01f, -10.0f, 10.0f);
    BreezePIDController_SetIntegralLimits(&pid, -0.5f, 0.5f);
    BreezePIDController_SetSetpoint(&pid, 10.0f);
    for (step_i = 0; step_i < 6; step_i++) run[step_i] = BreezePIDController_Compute(&pid, 0.0f);
    pvals("pid_position_integral_clamped_run", run, 6);
    pf("pid_integral_after_clamp", pid.integral);

    BreezePIDController_Init(&pid, BREEZE_PID_POSITION, 100.0f, 0.0f, 0.0f, 0.01f, -1.0f, 1.0f);
    BreezePIDController_SetSetpoint(&pid, 1.0f);
    for (step_i = 0; step_i < 6; step_i++) run[step_i] = BreezePIDController_Compute(&pid, pmeas[step_i]);
    pvals("pid_position_output_clamped_run", run, 6);

    BreezePIDController_Init(&pid, BREEZE_PID_POSITION, 2.0f, 0.5f, 0.1f, 0.01f, -10.0f, 10.0f);
    BreezePIDController_SetSetpoint(&pid, 1.0f);
    for (step_i = 0; step_i < 3; step_i++) (void)BreezePIDController_Compute(&pid, pmeas[step_i]);
    BreezePIDController_Reset(&pid);
    pf("pid_integral_after_reset", pid.integral);
    pf("pid_prev_error_after_reset", pid.prev_error);
    pf("pid_prev_output_after_reset", pid.prev_output);
    for (step_i = 0; step_i < 6; step_i++) run[step_i] = BreezePIDController_Compute(&pid, pmeas[step_i]);
    pvals("pid_run_after_reset", run, 6);

    /* --- state feedback, and the LQR that stores a model nobody reads ------- */
    BreezeStateFeedbackController sfc;
    const float K2[] = {1.5f, 0.5f};
    const float st2[] = {0.2f, -0.3f};
    const float K4[] = {1.0f, 2.0f, 3.0f, 4.0f};
    const float st4[] = {0.1f, 0.2f, 0.3f, 0.4f};

    printf("statefb_layout %zu %zu\n", sizeof sfc, _Alignof(BreezeStateFeedbackController));

    BreezeStateFeedbackController_Init(&sfc, K2, 2, 0.5f, -5.0f, 5.0f);
    pf("statefb_k0", sfc.K[0]);
    pf("statefb_k1", sfc.K[1]);
    pf("statefb_reference_init", sfc.reference);
    pf("statefb_n_init", sfc.N);
    pf("statefb_compute", BreezeStateFeedbackController_Compute(&sfc, st2));
    BreezeStateFeedbackController_SetReference(&sfc, 2.0f);
    pf("statefb_compute_with_reference", BreezeStateFeedbackController_Compute(&sfc, st2));
    BreezeStateFeedbackController_SetReference(&sfc, 100.0f);
    pf("statefb_compute_clamped_high", BreezeStateFeedbackController_Compute(&sfc, st2));
    BreezeStateFeedbackController_SetReference(&sfc, -100.0f);
    pf("statefb_compute_clamped_low", BreezeStateFeedbackController_Compute(&sfc, st2));

    BreezeStateFeedbackController_Init(&sfc, K4, 4, 1.0f, -100.0f, 100.0f);
    pf("statefb4_compute", BreezeStateFeedbackController_Compute(&sfc, st4));

    BreezeLQRController lqr;
    const float A2[4][4] = {{1.0f, 1.0f, 0.0f, 0.0f}, {0.0f, 1.0f, 0.0f, 0.0f}};
    const float B2[] = {0.0f, 1.0f};
    const float Q2[] = {1.0f, 1.0f};

    printf("lqr_layout %zu %zu\n", sizeof lqr, _Alignof(BreezeLQRController));

    BreezeLQRController_Init(&lqr, A2, B2, Q2, 0.1f, 2, 0.5f, -5.0f, 5.0f, 100, 1.0e-4f);
    /* Init stores the model and zeroes the gains: the Riccati solver it was
     * preparing for was never written, so none of these are read by anything. */
    pf("lqr_k0_after_init", lqr.K[0]);
    pf("lqr_k1_after_init", lqr.K[1]);
    pf("lqr_a00_stored", lqr.A[0][0]);
    pf("lqr_a01_stored", lqr.A[0][1]);
    pf("lqr_b1_stored", lqr.B[1]);
    pf("lqr_q0_stored", lqr.Q[0]);
    pf("lqr_r_stored", lqr.R);
    pf("lqr_max_iterations_stored", (float)lqr.max_iterations);
    pf("lqr_convergence_tol_stored", lqr.convergence_tol);

    /* With gains supplied from outside, the LQR computes exactly what the plain
     * state feedback controller computes - the two Compute functions are the
     * same code. */
    BreezeLQRController_SetGains(&lqr, K2);
    pf("lqr_compute", BreezeLQRController_Compute(&lqr, st2));
    BreezeLQRController_SetReference(&lqr, 2.0f);
    pf("lqr_compute_with_reference", BreezeLQRController_Compute(&lqr, st2));

    /* --- differential drive, driven by the fake platform ------------------ */
    BreezeDifferentialDrive dd;
    const BreezeDifferentialDriveConfig dd_cfg = {
        0.15f,   /* wheel_distance */
        0.03f,   /* wheel_radius */
        1.0f,    /* max_linear_speed */
        3.0f,    /* max_angular_speed */
        1,       /* left_motor_id */
        2,       /* right_motor_id */
        1,       /* left_encoder_id */
        2,       /* right_encoder_id */
        1000.0f  /* encoder_resolution */
    };

    BreezeDifferentialDrive_Init(&dd, dd_cfg, fake_set_motor, fake_get_encoder, 0.01f);

    /* Init starts both wheel PIDs with fixed gains and a +-1 output range. */
    pf("diffdrive_left_kp", dd.left_pid.kp);
    pf("diffdrive_left_ki", dd.left_pid.ki);
    pf("diffdrive_left_kd", dd.left_pid.kd);
    pf("diffdrive_left_output_min", dd.left_pid.output_min);
    pf("diffdrive_left_output_max", dd.left_pid.output_max);
    pf("diffdrive_right_kp", dd.right_pid.kp);
    pf("diffdrive_dt", dd.dt);
    pf("diffdrive_target_init", dd.target_linear_speed);

    BreezeDifferentialDrive_SetSpeed(&dd, 0.5f, 0.2f);
    pf("diffdrive_target_linear", dd.target_linear_speed);
    pf("diffdrive_target_angular", dd.target_angular_speed);

    /* SetSpeed clamps each component against its own maximum. */
    BreezeDifferentialDrive_SetSpeed(&dd, 5.0f, -9.0f);
    pf("diffdrive_clamped_linear", dd.target_linear_speed);
    pf("diffdrive_clamped_angular", dd.target_angular_speed);

    /* One full wheel revolution in 10 ms: 2*pi*r / dt. */
    pf("diffdrive_encoder_to_speed", BreezeDifferentialDrive_EncoderToSpeed(&dd, 1000.0f));

    /* Three control passes with the gains `Init` chose: SetSpeed, then Update,
     * reading a scripted encoder sequence and commanding the fake motors. */
    BreezeDifferentialDrive_SetSpeed(&dd, 0.5f, 0.2f);
    g_encoder_step = 0;
    float left_cmd[3];
    float right_cmd[3];
    for (step_i = 0; step_i < 3; step_i++) {
        g_motor_calls = 0;   /* reset per pass, or every pass records the first */
        g_encoder_step = step_i;
        BreezeDifferentialDrive_Update(&dd);
        left_cmd[step_i] = g_motor_speed[0];
        right_cmd[step_i] = g_motor_speed[1];
    }
    pvals("diffdrive_update_left", left_cmd, 3);
    pvals("diffdrive_update_right", right_cmd, 3);
    pi("diffdrive_left_motor_id", g_motor_id[0]);
    pi("diffdrive_right_motor_id", g_motor_id[1]);
    pi("diffdrive_encoder_reset_flag", g_encoder_reset);

    /* The same three passes with larger gains, on a *fresh* controller: a case
     * has to be reproducible from its own setup, not from the one before it.
     * (The first version of this reused `dd`, so the tuned run inherited the
     * untuned run's PID history and no fresh controller could reproduce it.) */
    BreezeDifferentialDrive ddt;
    BreezeDifferentialDrive_Init(&ddt, dd_cfg, fake_set_motor, fake_get_encoder, 0.01f);
    BreezeDifferentialDrive_SetPIDParams(&ddt, 2.0f, 0.5f, 0.25f);
    pf("diffdrive_setparams_left_kp", ddt.left_pid.kp);
    pf("diffdrive_setparams_right_kd", ddt.right_pid.kd);

    BreezeDifferentialDrive_SetSpeed(&ddt, 0.5f, 0.2f);
    g_encoder_step = 0;
    for (step_i = 0; step_i < 3; step_i++) {
        g_motor_calls = 0;
        g_encoder_step = step_i;
        BreezeDifferentialDrive_Update(&ddt);
        left_cmd[step_i] = g_motor_speed[0];
        right_cmd[step_i] = g_motor_speed[1];
    }
    pvals("diffdrive_update_tuned_left", left_cmd, 3);
    pvals("diffdrive_update_tuned_right", right_cmd, 3);

    /* --- omni drive: three wheels and four --------------------------------- */
    BreezeOmniDrive omni;
    int omni_motors[4] = {11, 12, 13, 14};
    int omni_encoders[4] = {1, 2, 3, 4};   /* the fake knows ids 1..4 */
    float omni_w0[3];
    float omni_w1[3];
    float omni_w2[3];
    float omni_w3[3];

    BreezeOmniDrive_Init(&omni, BREEZE_OMNI_THREE_WHEEL_120DEG, 0.03f, 0.1f, 1.0f, 3.0f,
                         omni_motors, omni_encoders, 1000.0f,
                         fake_set_motor, fake_get_encoder, 0.01f);
    pi("omni3_num_wheels", omni.config.num_wheels);
    pvals("omni3_angles", omni.config.wheel_angles, 3);
    pf("omni3_wheel_radius", omni.config.wheel_radius);
    pf("omni3_pid_kp", omni.wheel_pid[0].kp);
    pf("omni3_pid_output_max", omni.wheel_pid[0].output_max);
    pf("omni3_target_vx_init", omni.target_vx);

    BreezeOmniDrive_SetVelocity(&omni, 0.5f, 0.0f, 0.0f);
    pf("omni3_target_vx", omni.target_vx);

    /* The linear clamp is *radial*: (3, 4) has length 5, so both components
     * scale by 0.2 and the direction is preserved. */
    BreezeOmniDrive_SetVelocity(&omni, 3.0f, 4.0f, 0.0f);
    pf("omni3_clamped_vx", omni.target_vx);
    pf("omni3_clamped_vy", omni.target_vy);

    /* The angular clamp is per component, as elsewhere. */
    BreezeOmniDrive_SetVelocity(&omni, 0.0f, 0.0f, 9.0f);
    pf("omni3_angular_clamped", omni.target_omega);

    pf("omni3_encoder_to_speed", BreezeOmniDrive_EncoderToSpeed(&omni, 1000.0f));

    BreezeOmniDrive_SetPIDParams(&omni, 1.0f, 0.2f, 0.1f);
    pf("omni3_setparams_ki", omni.wheel_pid[2].ki);

    BreezeOmniDrive_SetVelocity(&omni, 0.3f, 0.1f, 0.2f);
    for (step_i = 0; step_i < 3; step_i++) {
        g_motor_calls = 0;
        g_encoder_step = step_i;
        BreezeOmniDrive_Update(&omni);
        omni_w0[step_i] = g_motor_speed[0];
        omni_w1[step_i] = g_motor_speed[1];
        omni_w2[step_i] = g_motor_speed[2];
    }
    pvals("omni3_run_wheel0", omni_w0, 3);
    pvals("omni3_run_wheel1", omni_w1, 3);
    pvals("omni3_run_wheel2", omni_w2, 3);
    pi("omni3_motor_id_0", g_motor_id[0]);
    pi("omni3_motor_id_2", g_motor_id[2]);

    /* The per-wheel rescale, which the run above never reaches: at the maximum
     * linear speed *and* full rotation the raw targets exceed the maximum, so
     * every wheel is scaled down together. Read back through the PID setpoints,
     * which is where `Update` puts the targets. */
    BreezeOmniDrive omni_fast;
    BreezeOmniDrive_Init(&omni_fast, BREEZE_OMNI_THREE_WHEEL_120DEG, 0.03f, 0.1f, 1.0f, 3.0f,
                         omni_motors, omni_encoders, 1000.0f,
                         fake_set_motor, fake_get_encoder, 0.01f);
    BreezeOmniDrive_SetVelocity(&omni_fast, 1.0f, 0.0f, 3.0f);
    g_motor_calls = 0;
    g_encoder_step = 0;
    BreezeOmniDrive_Update(&omni_fast);
    const float rescaled[3] = {
        omni_fast.wheel_pid[0].setpoint,
        omni_fast.wheel_pid[1].setpoint,
        omni_fast.wheel_pid[2].setpoint,
    };
    pvals("omni3_rescaled_targets", rescaled, 3);
    pvals("omni3_unclamped_velocity", (const float[]){omni_fast.target_vx, omni_fast.target_omega}, 2);

    /* Pure rotation. The C inverse kinematics adds the same
     * `wheel_distance * omega` to *every* wheel, so all three targets come out
     * equal - which is not what a rotation does when the wheels sit at
     * different angles. Recorded, not corrected: the port reproduces it and the
     * Zig test asserts the equality so the behaviour is pinned (REVIEW §36). */
    BreezeOmniDrive omni_rot;
    BreezeOmniDrive_Init(&omni_rot, BREEZE_OMNI_THREE_WHEEL_120DEG, 0.03f, 0.1f, 1.0f, 3.0f,
                         omni_motors, omni_encoders, 1000.0f,
                         fake_set_motor, fake_get_encoder, 0.01f);
    BreezeOmniDrive_SetVelocity(&omni_rot, 0.0f, 0.0f, 1.0f);
    float rot0[3];
    float rot1[3];
    float rot2[3];
    for (step_i = 0; step_i < 3; step_i++) {
        g_motor_calls = 0;
        g_encoder_step = step_i;
        BreezeOmniDrive_Update(&omni_rot);
        rot0[step_i] = g_motor_speed[0];
        rot1[step_i] = g_motor_speed[1];
        rot2[step_i] = g_motor_speed[2];
    }
    pvals("omni3_pure_rotation_wheel0", rot0, 3);
    pvals("omni3_pure_rotation_wheel1", rot1, 3);
    pvals("omni3_pure_rotation_wheel2", rot2, 3);

    /* Four wheels, 90 degrees apart. */
    BreezeOmniDrive omni4;
    BreezeOmniDrive_Init(&omni4, BREEZE_OMNI_FOUR_WHEEL_90DEG, 0.03f, 0.12f, 1.0f, 3.0f,
                         omni_motors, omni_encoders, 1000.0f,
                         fake_set_motor, fake_get_encoder, 0.01f);
    pi("omni4_num_wheels", omni4.config.num_wheels);
    pvals("omni4_angles", omni4.config.wheel_angles, 4);

    BreezeOmniDrive_SetVelocity(&omni4, 0.3f, 0.1f, 0.2f);
    for (step_i = 0; step_i < 3; step_i++) {
        g_motor_calls = 0;
        g_encoder_step = step_i;
        BreezeOmniDrive_Update(&omni4);
        omni_w3[step_i] = g_motor_speed[3];
    }
    pvals("omni4_run_wheel3", omni_w3, 3);
    pi("omni4_motor_id_3", g_motor_id[3]);

    /* --- mecanum drive ----------------------------------------------------- */
    /* Same shape as the omni platform, and its inverse kinematics is the
     * contrast worth recording: the rotation term *does* differ per wheel here
     * (front-left and rear-left get -omega, front-right and rear-right +omega),
     * which is what a rotation needs. */
    BreezeMecanumDrive md;
    const BreezeMecanumDriveConfig md_cfg = {
        0.03f,   /* wheel_radius */
        0.2f,    /* wheel_distance_x */
        0.16f,   /* wheel_distance_y */
        1.0f,    /* max_linear_speed */
        3.0f,    /* max_angular_speed */
        {11, 12, 13, 14},
        {1, 2, 3, 4},
        1000.0f  /* encoder_resolution */
    };
    float mw0[3];
    float mw1[3];
    float mw2[3];
    float mw3[3];

    BreezeMecanumDrive_Init(&md, md_cfg, fake_set_motor, fake_get_encoder, 0.01f);
    pf("mecanum_pid_kp", md.wheel_pid[0].kp);
    pf("mecanum_pid_output_max", md.wheel_pid[0].output_max);
    pf("mecanum_target_vx_init", md.target_vx);

    BreezeMecanumDrive_SetVelocity(&md, 0.3f, -0.2f, 0.1f);
    pf("mecanum_target_vx", md.target_vx);
    pf("mecanum_target_vy", md.target_vy);
    pf("mecanum_target_omega", md.target_omega);

    /* Radial clamp on the linear part, per-component on the angular part. */
    BreezeMecanumDrive_SetVelocity(&md, 3.0f, 4.0f, 9.0f);
    pf("mecanum_clamped_vx", md.target_vx);
    pf("mecanum_clamped_vy", md.target_vy);
    pf("mecanum_clamped_omega", md.target_omega);

    pf("mecanum_encoder_to_speed", BreezeMecanumDrive_EncoderToSpeed(&md, 1000.0f));

    BreezeMecanumDrive_SetPIDParams(&md, 1.0f, 0.2f, 0.1f);
    pf("mecanum_setparams_ki", md.wheel_pid[3].ki);

    BreezeMecanumDrive_SetVelocity(&md, 0.3f, -0.2f, 0.1f);
    for (step_i = 0; step_i < 3; step_i++) {
        g_motor_calls = 0;
        g_encoder_step = step_i;
        BreezeMecanumDrive_Update(&md);
        mw0[step_i] = g_motor_speed[0];
        mw1[step_i] = g_motor_speed[1];
        mw2[step_i] = g_motor_speed[2];
        mw3[step_i] = g_motor_speed[3];
    }
    pvals("mecanum_run_wheel0", mw0, 3);
    pvals("mecanum_run_wheel1", mw1, 3);
    pvals("mecanum_run_wheel2", mw2, 3);
    pvals("mecanum_run_wheel3", mw3, 3);
    pi("mecanum_motor_id_0", g_motor_id[0]);
    pi("mecanum_motor_id_3", g_motor_id[3]);

    /* Targets read back from the PID setpoints, where `Update` puts them. A pure
     * rotation gives two values with opposite signs. */
    BreezeMecanumDrive md_rot;
    BreezeMecanumDrive_Init(&md_rot, md_cfg, fake_set_motor, fake_get_encoder, 0.01f);
    BreezeMecanumDrive_SetVelocity(&md_rot, 0.0f, 0.0f, 1.0f);
    g_motor_calls = 0;
    g_encoder_step = 0;
    BreezeMecanumDrive_Update(&md_rot);
    const float mecanum_rot[4] = {
        md_rot.wheel_pid[0].setpoint,
        md_rot.wheel_pid[1].setpoint,
        md_rot.wheel_pid[2].setpoint,
        md_rot.wheel_pid[3].setpoint,
    };
    pvals("mecanum_pure_rotation_targets", mecanum_rot, 4);

    /* Full speed plus full rotation: the per-wheel rescale fires. */
    BreezeMecanumDrive md_fast;
    BreezeMecanumDrive_Init(&md_fast, md_cfg, fake_set_motor, fake_get_encoder, 0.01f);
    BreezeMecanumDrive_SetVelocity(&md_fast, 1.0f, 0.0f, 3.0f);
    g_motor_calls = 0;
    g_encoder_step = 0;
    BreezeMecanumDrive_Update(&md_fast);
    const float mecanum_fast[4] = {
        md_fast.wheel_pid[0].setpoint,
        md_fast.wheel_pid[1].setpoint,
        md_fast.wheel_pid[2].setpoint,
        md_fast.wheel_pid[3].setpoint,
    };
    pvals("mecanum_rescaled_targets", mecanum_fast, 4);

    /* --- ackermann steering ------------------------------------------------ */
    BreezeAckermannSteering ak;
    const BreezeAckermannConfig ak_cfg = {
        0.3f,    /* wheelbase */
        0.2f,    /* track_width */
        0.03f,   /* wheel_radius */
        1.5f,    /* max_speed */
        0.5f,    /* max_steering_angle */
        1,       /* drive_motor_id */
        2,       /* steering_motor_id */
        1,       /* encoder_id */
        1000.0f, /* encoder_resolution */
        1.0f     /* steering_ratio - stored and never read by anything */
    };
    float ak_inner;
    float ak_outer;

    BreezeAckermannSteering_Init(&ak, ak_cfg, fake_set_motor, fake_get_encoder, 0.01f);
    pf("ackermann_speed_pid_kp", ak.speed_pid.kp);
    pf("ackermann_speed_pid_output_max", ak.speed_pid.output_max);
    pf("ackermann_steering_pid_kp", ak.steering_pid.kp);
    pf("ackermann_target_speed_init", ak.target_speed);

    BreezeAckermannSteering_SetTargets(&ak, 0.5f, 0.2f);
    pf("ackermann_target_speed", ak.target_speed);
    pf("ackermann_target_steering", ak.target_steering_angle);

    /* Speed and steering are clamped separately, each to its own maximum. */
    BreezeAckermannSteering_SetTargets(&ak, 9.0f, -9.0f);
    pf("ackermann_clamped_speed", ak.target_speed);
    pf("ackermann_clamped_steering", ak.target_steering_angle);

    pf("ackermann_encoder_to_speed", BreezeAckermannSteering_EncoderToSpeed(&ak, 1000.0f));

    /* The Ackermann geometry, and the place where turn direction is lost: above
     * the small-angle branch the sign of the input disappears, against the
     * function's own comment. The left and right cases below come out identical,
     * while the small-angle pair comes out opposite - so the function is
     * discontinuous in how it treats sign. */
    BreezeAckermannSteering_CalculateWheelAngles(&ak, 0.2f, &ak_inner, &ak_outer);
    pf("ackermann_angles_left_inner", ak_inner);
    pf("ackermann_angles_left_outer", ak_outer);

    BreezeAckermannSteering_CalculateWheelAngles(&ak, -0.2f, &ak_inner, &ak_outer);
    pf("ackermann_angles_right_inner", ak_inner);
    pf("ackermann_angles_right_outer", ak_outer);

    BreezeAckermannSteering_CalculateWheelAngles(&ak, 0.005f, &ak_inner, &ak_outer);
    pf("ackermann_angles_small_pos_inner", ak_inner);
    pf("ackermann_angles_small_pos_outer", ak_outer);

    BreezeAckermannSteering_CalculateWheelAngles(&ak, -0.005f, &ak_inner, &ak_outer);
    pf("ackermann_angles_small_neg_inner", ak_inner);
    pf("ackermann_angles_small_neg_outer", ak_outer);

    BreezeAckermannSteering_CalculateWheelAngles(&ak, 0.0f, &ak_inner, &ak_outer);
    pf("ackermann_angles_zero_inner", ak_inner);

    /* One update. The steering output is a plain feedforward division, so the
     * steering PID's setpoint is written and never computed - its integral is
     * still zero afterwards. That is how the corpus records a knob that turns
     * nothing. */
    BreezeAckermannSteering_SetTargets(&ak, 0.4f, 0.3f);
    g_motor_calls = 0;
    g_encoder_step = 0;
    BreezeAckermannSteering_Update(&ak);
    pf("ackermann_speed_setpoint", ak.speed_pid.setpoint);
    pf("ackermann_steering_setpoint", ak.steering_pid.setpoint);
    pf("ackermann_steering_integral_after", ak.steering_pid.integral);
    pvals("ackermann_update_motors", g_motor_speed, 2);
    pi("ackermann_drive_motor_id", g_motor_id[0]);
    pi("ackermann_steering_motor_id", g_motor_id[1]);

    /* Three passes on a *fresh* controller: a case is reproducible from its own
     * setup (REVIEW §35), and the run above left the speed PID with history. */
    float ak_drive[3];
    float ak_steer[3];
    BreezeAckermannSteering ak_run;
    BreezeAckermannSteering_Init(&ak_run, ak_cfg, fake_set_motor, fake_get_encoder, 0.01f);
    BreezeAckermannSteering_SetTargets(&ak_run, 0.4f, 0.3f);
    for (step_i = 0; step_i < 3; step_i++) {
        g_motor_calls = 0;
        g_encoder_step = step_i;
        BreezeAckermannSteering_Update(&ak_run);
        ak_drive[step_i] = g_motor_speed[0];
        ak_steer[step_i] = g_motor_speed[1];
    }
    pvals("ackermann_run_drive", ak_drive, 3);
    pvals("ackermann_run_steering", ak_steer, 3);

    /* --- MRAC ------------------------------------------------------------- */
    BreezeMRAC mrac;
    const float mrac_y[] = {0.0f, 0.1f, 0.25f, 0.5f, 0.8f};

    BreezeMRAC_Init(&mrac, -1.0f, 2.0f, 0.5f, 0.75f, -10.0f, 10.0f, 0.01f);
    pf("mrac_theta0_init", mrac.theta[0]);
    pf("mrac_theta1_init", mrac.theta[1]);
    pf("mrac_gamma0", mrac.gamma[0]);
    pf("mrac_gamma1", mrac.gamma[1]);
    pf("mrac_x_m_init", mrac.x_m);
    pf("mrac_prev_x_init", mrac.prev_x);

    for (step_i = 0; step_i < 5; step_i++) run[step_i] = BreezeMRAC_Update(&mrac, 1.0f, mrac_y[step_i]);
    pvals("mrac_run", run, 5);
    pf("mrac_theta0_after", mrac.theta[0]);
    pf("mrac_theta1_after", mrac.theta[1]);
    pf("mrac_x_m_after", mrac.x_m);

    /* `prev_x` and `prev_u` are written on every update and read by nothing.
     * They are state a caller can inspect, so they are recorded rather than
     * dropped - unlike a configuration input nothing reads (REVIEW §33, §38). */
    pf("mrac_prev_x_after", mrac.prev_x);
    pf("mrac_prev_u_after", mrac.prev_u);

    /* A large reference with a tight output limit: the control input clamps while
     * the adaptation keeps running underneath. */
    BreezeMRAC mrac_clamped;
    BreezeMRAC_Init(&mrac_clamped, -1.0f, 2.0f, 100.0f, 100.0f, -0.5f, 0.5f, 0.01f);
    for (step_i = 0; step_i < 5; step_i++) run[step_i] = BreezeMRAC_Update(&mrac_clamped, 10.0f, 0.0f);
    pvals("mrac_clamped_run", run, 5);
    pf("mrac_clamped_theta0_after", mrac_clamped.theta[0]);

    /* --- self-tuning PID -------------------------------------------------- */
    BreezeAdaptivePID apid;
    BreezeAdaptivePID_Init(&apid, BREEZE_PID_POSITION, 2.0f, 0.5f, 0.1f, 0.01f, -5.0f, 5.0f,
                           0.1f, 0.5f, 3);
    pf("adaptive_kp_min", apid.kp_min);
    pf("adaptive_kp_max", apid.kp_max);
    pf("adaptive_ki_min", apid.ki_min);
    pf("adaptive_kd_max", apid.kd_max);
    pf("adaptive_period", (float)apid.adaptation_period);
    pf("adaptive_pid_kp_init", apid.pid.kp);
    pf("adaptive_prev_error_init", apid.prev_error);
    pf("adaptive_prev_output_init", apid.prev_output);

    for (step_i = 0; step_i < 6; step_i++) run[step_i] = BreezeAdaptivePID_Compute(&apid, 3.0f, pmeas[step_i]);
    pvals("adaptive_run", run, 6);
    pf("adaptive_kp_after", apid.pid.kp);
    pf("adaptive_ki_after", apid.pid.ki);
    pf("adaptive_kd_after", apid.pid.kd);
    pf("adaptive_prev_error_after", apid.prev_error);
    pf("adaptive_prev_output_after", apid.prev_output);
    pf("adaptive_counter_after", (float)apid.adaptation_counter);

    /* A small error never adapts: the threshold gates the whole block. */
    BreezeAdaptivePID apid_quiet;
    BreezeAdaptivePID_Init(&apid_quiet, BREEZE_PID_POSITION, 2.0f, 0.5f, 0.1f, 0.01f, -5.0f, 5.0f,
                           0.1f, 0.5f, 3);
    for (step_i = 0; step_i < 6; step_i++) run[step_i] = BreezeAdaptivePID_Compute(&apid_quiet, 1.0f, 0.99f);
    pvals("adaptive_quiet_run", run, 6);
    pf("adaptive_quiet_kp_after", apid_quiet.pid.kp);
    pf("adaptive_quiet_counter_after", (float)apid_quiet.adaptation_counter);

    /* A large adaptation rate with a step error drives all three gains into
     * their limits - the ordinary run moves them by a few thousandths and never
     * gets near one. Without this case, deleting the gain clamp passed every
     * test. */
    BreezeAdaptivePID apid_fast;
    BreezeAdaptivePID_Init(&apid_fast, BREEZE_PID_POSITION, 2.0f, 0.5f, 0.1f, 0.01f, -50.0f, 50.0f,
                           50.0f, 0.1f, 1);
    for (step_i = 0; step_i < 4; step_i++) run[step_i] = BreezeAdaptivePID_Compute(&apid_fast, 10.0f, 0.0f);
    pvals("adaptive_fast_run", run, 4);
    pf("adaptive_fast_kp_after", apid_fast.pid.kp);
    pf("adaptive_fast_ki_after", apid_fast.pid.ki);
    pf("adaptive_fast_kd_after", apid_fast.pid.kd);

    /* --- balance controller ------------------------------------------------ */
    BreezeBalanceController bal;
    const BreezeBalanceControllerConfig bal_cfg = {
        0.03f,   /* wheel_radius */
        0.15f,   /* wheel_distance */
        0.5f,    /* max_tilt_angle */
        1.0f,    /* max_speed */
        3.0f,    /* max_angular_speed */
        0.0f,    /* target_tilt_angle */
        1,       /* left_motor_id */
        2,       /* right_motor_id */
        1,       /* left_encoder_id */
        2,       /* right_encoder_id */
        1000.0f  /* encoder_resolution */
    };
    int bal_ok[5];
    float bal_left[5];
    float bal_right[5];

    BreezeBalanceController_Init(&bal, bal_cfg, fake_set_motor, fake_get_encoder, fake_get_imu, 0.01f);
    pf("balance_angle_kp", bal.angle_pid.kp);
    pf("balance_angle_kd", bal.angle_pid.kd);
    pf("balance_angle_output_max", bal.angle_pid.output_max);
    pf("balance_speed_kp", bal.speed_pid.kp);
    pf("balance_speed_output_max", bal.speed_pid.output_max);
    pf("balance_turn_kp", bal.turn_pid.kp);
    pf("balance_filter_alpha", bal.imu_filter.alpha);
    pf("balance_filter_dt", bal.imu_filter.dt);
    pf("balance_current_angle_init", bal.current_angle);

    BreezeBalanceController_SetTargets(&bal, 0.5f, 0.2f);
    pf("balance_target_speed", bal.target_speed);
    pf("balance_target_turn", bal.target_turn_rate);
    BreezeBalanceController_SetTargets(&bal, 9.0f, -9.0f);
    pf("balance_clamped_speed", bal.target_speed);
    pf("balance_clamped_turn", bal.target_turn_rate);
    pf("balance_encoder_to_speed", BreezeBalanceController_EncoderToSpeed(&bal, 1000.0f));

    /* Three passes on the mild script: the estimated angle and speed, the return
     * value, and the two motor commands. */
    BreezeBalanceController_SetTargets(&bal, 0.3f, 0.1f);
    for (step_i = 0; step_i < 3; step_i++) {
        g_motor_calls = 0;
        g_encoder_step = step_i;
        bal_ok[step_i] = BreezeBalanceController_Update(&bal);
        bal_left[step_i] = g_motor_speed[0];
        bal_right[step_i] = g_motor_speed[1];
    }
    pvals("balance_run_ok", (const float[]){bal_ok[0], bal_ok[1], bal_ok[2]}, 3);
    pvals("balance_run_left", bal_left, 3);
    pvals("balance_run_right", bal_right, 3);
    pf("balance_current_angle_after", bal.current_angle);
    pf("balance_current_speed_after", bal.current_speed);

    /* An IMU read failure: update reports it and commands nothing at all. */
    BreezeBalanceController bal_fail;
    BreezeBalanceController_Init(&bal_fail, bal_cfg, fake_set_motor, fake_get_encoder, fake_get_imu, 0.01f);
    g_imu_fail = 1;
    g_motor_calls = 0;
    g_encoder_step = 0;
    pi("balance_imu_failure_ok", BreezeBalanceController_Update(&bal_fail));
    pi("balance_imu_failure_motor_calls", g_motor_calls);
    g_imu_fail = 0;

    /* Past the safety limit: the motors are zeroed and update reports 0. The
     * script's rate drives the estimate up one pass at a time, so the first four
     * passes are still balanced. */
    BreezeBalanceController bal_tilt;
    BreezeBalanceController_Init(&bal_tilt, bal_cfg, fake_set_motor, fake_get_encoder, fake_get_imu, 0.01f);
    g_imu_tilt = 1;
    for (step_i = 0; step_i < 5; step_i++) {
        g_motor_calls = 0;
        g_encoder_step = step_i;
        bal_ok[step_i] = BreezeBalanceController_Update(&bal_tilt);
        bal_left[step_i] = g_motor_speed[0];
        bal_right[step_i] = g_motor_speed[1];
    }
    pvals("balance_tilt_ok", (const float[]){bal_ok[0], bal_ok[1], bal_ok[2], bal_ok[3], bal_ok[4]}, 5);
    pvals("balance_tilt_left", bal_left, 5);
    pvals("balance_tilt_right", bal_right, 5);
    pf("balance_tilt_angle_after", bal_tilt.current_angle);
    g_imu_tilt = 0;

    /* --- fuzzy controller --------------------------------------------------- */
    /* Three sets per variable, the classic 3x3 error/rate table. */
    BreezeFuzzyMembership fuzzy_sets[3] = {
        {BREEZE_FUZZY_TRIANGULAR, {-1.0f, -1.0f, 0.0f}, "NEG"},
        {BREEZE_FUZZY_TRIANGULAR, {-1.0f, 0.0f, 1.0f}, "ZERO"},
        {BREEZE_FUZZY_TRIANGULAR, {0.0f, 1.0f, 1.0f}, "POS"},
    };
    BreezeFuzzyRule fuzzy_rules[9] = {
        {0, 0, 0}, {0, 1, 0}, {0, 2, 1},
        {1, 0, 0}, {1, 1, 1}, {1, 2, 2},
        {2, 0, 1}, {2, 1, 2}, {2, 2, 2},
    };
    BreezeFuzzyController fz;

    BreezeFuzzyController_Init(&fz, -1.0f, 1.0f, -1.0f, 1.0f, -1.0f, 1.0f, 5);
    BreezeFuzzyController_SetInput1Memberships(&fz, fuzzy_sets, 3);
    BreezeFuzzyController_SetInput2Memberships(&fz, fuzzy_sets, 3);
    BreezeFuzzyController_SetOutputMemberships(&fz, fuzzy_sets, 3);
    BreezeFuzzyController_SetRules(&fz, fuzzy_rules, 9);

    pf("fuzzy_input1_min", fz.input1_min);
    pf("fuzzy_discretization_level", (float)fz.discretization_level);

    /* Membership functions, including the boundaries where the branches change. */
    pf("fuzzy_tri_left", BreezeFuzzyController_TriangularMembership(-0.5f, -1.0f, 0.0f, 1.0f));
    pf("fuzzy_tri_centre", BreezeFuzzyController_TriangularMembership(0.0f, -1.0f, 0.0f, 1.0f));
    pf("fuzzy_tri_right", BreezeFuzzyController_TriangularMembership(0.5f, -1.0f, 0.0f, 1.0f));
    pf("fuzzy_tri_at_a", BreezeFuzzyController_TriangularMembership(-1.0f, -1.0f, 0.0f, 1.0f));
    pf("fuzzy_tri_at_c", BreezeFuzzyController_TriangularMembership(1.0f, -1.0f, 0.0f, 1.0f));
    /* A degenerate triangle, where b == a: the left branch divides by zero. */
    pf("fuzzy_tri_degenerate", BreezeFuzzyController_TriangularMembership(-1.0f, -1.0f, -1.0f, 1.0f));

    pf("fuzzy_trap_left", BreezeFuzzyController_TrapezoidalMembership(0.1f, 0.0f, 0.2f, 0.5f, 1.0f));
    pf("fuzzy_trap_shoulder", BreezeFuzzyController_TrapezoidalMembership(0.3f, 0.0f, 0.2f, 0.5f, 1.0f));
    pf("fuzzy_trap_right", BreezeFuzzyController_TrapezoidalMembership(0.75f, 0.0f, 0.2f, 0.5f, 1.0f));

    pf("fuzzy_gauss_centre", BreezeFuzzyController_GaussianMembership(0.0f, 0.0f, 0.5f));
    pf("fuzzy_gauss_one_sigma", BreezeFuzzyController_GaussianMembership(0.5f, 0.0f, 0.5f));
    pf("fuzzy_gauss_far", BreezeFuzzyController_GaussianMembership(2.0f, 0.0f, 0.5f));

    /* The grid the first compute call builds, printed while it exists. */
    (void)BreezeFuzzyController_Compute(&fz, 0.0f, 0.0f);
    pvals("fuzzy_grid", fz.output_discretization, 5);

    /* The centroid over the rule table. */
    pf("fuzzy_compute_zero", BreezeFuzzyController_Compute(&fz, 0.0f, 0.0f));
    pf("fuzzy_compute_pos_pos", BreezeFuzzyController_Compute(&fz, 0.8f, 0.8f));
    pf("fuzzy_compute_neg_neg", BreezeFuzzyController_Compute(&fz, -0.8f, -0.8f));
    pf("fuzzy_compute_mixed", BreezeFuzzyController_Compute(&fz, 0.5f, -0.5f));
    /* Inputs outside the range are clamped to it. */
    pf("fuzzy_compute_clamped_high", BreezeFuzzyController_Compute(&fz, 9.0f, 9.0f));
    pf("fuzzy_compute_clamped_low", BreezeFuzzyController_Compute(&fz, -9.0f, -9.0f));

    /* No rules: the C returns 0 before allocating anything. */
    BreezeFuzzyController fz_bare;
    BreezeFuzzyController_Init(&fz_bare, -1.0f, 1.0f, -1.0f, 1.0f, -1.0f, 1.0f, 5);
    pf("fuzzy_compute_no_rules", BreezeFuzzyController_Compute(&fz_bare, 0.5f, 0.5f));
    pi("fuzzy_no_rules_grid_allocated", fz_bare.output_discretization != NULL);

    /* A rule whose output set is entirely outside the output range: every grid
     * point has zero membership, so the denominator stays zero and the C answers
     * with the midpoint of the output range. */
    BreezeFuzzyMembership fuzzy_far[1] = {
        {BREEZE_FUZZY_TRIANGULAR, {5.0f, 6.0f, 7.0f}, "FAR"},
    };
    BreezeFuzzyController fz_far;
    BreezeFuzzyController_Init(&fz_far, -1.0f, 1.0f, -1.0f, 1.0f, -1.0f, 1.0f, 5);
    BreezeFuzzyController_SetInput1Memberships(&fz_far, fuzzy_sets, 3);
    BreezeFuzzyController_SetInput2Memberships(&fz_far, fuzzy_sets, 3);
    BreezeFuzzyController_SetOutputMemberships(&fz_far, fuzzy_far, 1);
    BreezeFuzzyController_SetRules(&fz_far, fuzzy_rules, 1);
    pf("fuzzy_compute_empty_consequent", BreezeFuzzyController_Compute(&fz_far, 0.5f, 0.5f));

    BreezeFuzzyController_Free(&fz);
    pi("fuzzy_grid_freed", fz.output_discretization == NULL);

    return 0;
}
